import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'base_interface',
        'interface_utilisation',
        'kinetics',
        'lithium_plating',
        'open_circuit_potential',
        'sei',
        'total_interfacial_current',
    },
    submod_attrs={
        'base_interface': [
            'BaseInterface',
        ],
        'interface_utilisation': [
            'BaseModel',
            'Constant',
            'CurrentDriven',
            'Full',
            'base_utilisation',
            'constant_utilisation',
            'current_driven_utilisation',
            'full_utilisation',
        ],
        'kinetics': [
            'AsymmetricButlerVolmer',
            'BaseKinetics',
            'CurrentForInverseButlerVolmer',
            'CurrentForInverseButlerVolmerLithiumMetal',
            'DiffusionLimited',
            'ForwardTafel',
            'InverseButlerVolmer',
            'Linear',
            'MSMRButlerVolmer',
            'Marcus',
            'MarcusHushChidsey',
            'NoReaction',
            'SymmetricButlerVolmer',
            'TotalMainKinetics',
            'base_kinetics',
            'butler_volmer',
            'diffusion_limited',
            'inverse_butler_volmer',
            'inverse_kinetics',
            'linear',
            'marcus',
            'msmr_butler_volmer',
            'no_reaction',
            'tafel',
            'total_main_kinetics',
        ],
        'lithium_plating': [
            'BasePlating',
            'NoPlating',
            'Plating',
            'base_plating',
            'no_plating',
            'plating',
        ],
        'open_circuit_potential': [
            'BaseOpenCircuitPotential',
            'CurrentSigmoidOpenCircuitPotential',
            'MSMROpenCircuitPotential',
            'SingleOpenCircuitPotential',
            'base_ocp',
            'current_sigmoid_ocp',
            'msmr_ocp',
            'single_ocp',
        ],
        'sei': [
            'BaseModel',
            'ConstantSEI',
            'NoSEI',
            'SEIGrowth',
            'TotalSEI',
            'base_sei',
            'constant_sei',
            'no_sei',
            'sei_growth',
            'total_sei',
        ],
        'total_interfacial_current': [
            'TotalInterfacialCurrent',
        ],
    },
)

__all__ = ['AsymmetricButlerVolmer', 'BaseInterface', 'BaseKinetics',
           'BaseModel', 'BaseOpenCircuitPotential', 'BasePlating', 'Constant',
           'ConstantSEI', 'CurrentDriven', 'CurrentForInverseButlerVolmer',
           'CurrentForInverseButlerVolmerLithiumMetal',
           'CurrentSigmoidOpenCircuitPotential', 'DiffusionLimited',
           'ForwardTafel', 'Full', 'InverseButlerVolmer', 'Linear',
           'MSMRButlerVolmer', 'MSMROpenCircuitPotential', 'Marcus',
           'MarcusHushChidsey', 'NoPlating', 'NoReaction', 'NoSEI', 'Plating',
           'SEIGrowth', 'SingleOpenCircuitPotential', 'SymmetricButlerVolmer',
           'TotalInterfacialCurrent', 'TotalMainKinetics', 'TotalSEI',
           'base_interface', 'base_kinetics', 'base_ocp', 'base_plating',
           'base_sei', 'base_utilisation', 'butler_volmer', 'constant_sei',
           'constant_utilisation', 'current_driven_utilisation',
           'current_sigmoid_ocp', 'diffusion_limited', 'full_utilisation',
           'interface_utilisation', 'inverse_butler_volmer',
           'inverse_kinetics', 'kinetics', 'linear', 'lithium_plating',
           'marcus', 'msmr_butler_volmer', 'msmr_ocp', 'no_plating',
           'no_reaction', 'no_sei', 'open_circuit_potential', 'plating', 'sei',
           'sei_growth', 'single_ocp', 'tafel', 'total_interfacial_current',
           'total_main_kinetics', 'total_sei']
