"""Rendering the committed model zoo docs pages and status badges.

The files are generated and committed rather than built inside Sphinx, which
keeps the ``-W`` docs build deterministic and offline. Because the renderers live
here rather than in the script, the ``docs`` contract check can compare a page
against what it *should* contain instead of merely asserting it exists.

``scripts/generate.py`` is the command-line wrapper around this module.
"""

from __future__ import annotations

import json
from pathlib import Path

from pybamm_model_zoo._paths import BADGES_DIR, DOCS_DIR, STATUS_FILE
from pybamm_model_zoo._registry import ModelEntry

MODELS_DIR = DOCS_DIR / "models"
GENERATED_BY = (
    "<!-- Generated by packages/pybamm-model-zoo/scripts/generate.py. "
    "Do not edit by hand. -->"
)
# Depth from docs/source/model_zoo/models/<slug>.md back to the repository root.
README_PREFIX = "../../../../packages/pybamm-model-zoo/src/pybamm_model_zoo"
BADGE_COLORS = {"pass": "brightgreen", "fail": "red", "untested": "lightgrey"}
BADGE_LABEL = "model zoo"

_INDEX_HEADER = """\
(model_zoo)=

{generated}

# Model zoo

Community- and partner-contributed PyBaMM models. Each entry is one
self-contained folder with its own maintainer, tests, examples, and
citation; the table below is generated from those folders' manifests.

Zoo models are reached through the zoo's registry, not the `pybamm`
namespace:

```python
import pybamm
import pybamm_model_zoo as zoo

model = zoo.load(zoo.list_models()[0])()
solution = pybamm.Simulation(model).solve([0, 3600])
```

Models in the **core** tier are covered by PyBaMM's merge gate. Models in
the **community** tier are tested on every pull request too, but their
results are advisory: a red community model never blocks a PyBaMM merge.
See [contributing a model](contributing.md) to add your own.

| Model | Tier | Maintainer | PyBaMM | Added |
| --- | --- | --- | --- | --- |
"""

_COMPATIBILITY_HEADER = """\

## Compatibility

Refreshed weekly by the `model_zoo_status` workflow, which runs each model
against every release its `pybamm_requires` admits, plus `main`.

| Model | Results | Last passing |
| --- | --- | --- |
"""

_TOCTREE = """
```{toctree}
:hidden:
:maxdepth: 1

Contributing a model <contributing>
"""


def version_key(version: str) -> tuple[int, list[int]]:
    """Sort CalVer releases numerically, and sort anything else (``main``) last."""
    try:
        return (0, [int(part) for part in version.split(".")])
    except ValueError:
        return (1, [])


def read_status(path: Path | None = None) -> dict:
    """The committed compatibility results, or an empty set of them."""
    path = path or STATUS_FILE
    if not path.is_file():
        return {"models": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def collect_results(results_dir: Path, generated: str) -> dict:
    """Fold one JSON file per matrix cell into the ``status.json`` shape."""
    models: dict[str, dict[str, str]] = {}
    for path in sorted(Path(results_dir).glob("*.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        models.setdefault(record["model"], {})[record["version"]] = record["result"]

    status: dict = {"generated": generated, "models": {}}
    for model, results in sorted(models.items()):
        passing = [
            version
            for version, result in results.items()
            if result == "pass" and version != "main"
        ]
        status["models"][model] = {
            "results": dict(
                sorted(results.items(), key=lambda item: version_key(item[0]))
            ),
            "last_pass": max(passing, key=version_key) if passing else None,
        }
    return status


def badge(record: dict) -> dict:
    """The shields.io endpoint payload for one model's status record."""
    results = record.get("results", {})
    failing = sorted(
        (version for version, result in results.items() if result != "pass"),
        key=version_key,
    )
    if not results:
        message, color = "untested", BADGE_COLORS["untested"]
    elif failing:
        message, color = f"failing on {', '.join(failing)}", BADGE_COLORS["fail"]
    else:
        message = f"passing ({record.get('last_pass') or 'latest'})"
        color = BADGE_COLORS["pass"]
    return {
        "schemaVersion": 1,
        "label": BADGE_LABEL,
        "message": message,
        "color": color,
    }


def maintainer_links(entry: ModelEntry) -> str:
    """Maintainers, linked to their profiles.

    Team handles are left as plain text: GitHub team pages are not reachable
    anonymously, so linking one would be a dead link to most readers.
    """
    return ", ".join(
        f"@{maintainer.github}"
        if "/" in maintainer.github
        else f"[@{maintainer.github}](https://github.com/{maintainer.github})"
        for maintainer in entry.maintainers
    )


def status_cell(record: dict) -> str:
    results = record.get("results", {})
    if not results:
        return "not yet run"
    return ", ".join(
        f"`{version}`: {result}"
        for version, result in sorted(
            results.items(), key=lambda item: version_key(item[0])
        )
    )


def index_page(entries: list[ModelEntry], status: dict) -> str:
    """The model zoo landing page: the model table and the compatibility table."""
    records = status.get("models", {})
    rows = [
        f"| [{entry.title}](models/{entry.slug}.md) | {entry.tier} | "
        f"{maintainer_links(entry)} | `{entry.pybamm_requires}` | {entry.added} |"
        for entry in entries
    ]
    status_rows = [
        f"| {entry.slug} | {status_cell(records.get(entry.slug, {}))} | "
        f"{records.get(entry.slug, {}).get('last_pass') or '—'} |"
        for entry in entries
    ]
    toctree = (
        _TOCTREE + "".join(f"models/{entry.slug}\n" for entry in entries) + "```\n"
    )
    return (
        _INDEX_HEADER.format(generated=GENERATED_BY)
        + "\n".join(rows)
        + "\n"
        + _COMPATIBILITY_HEADER
        + "\n".join(status_rows)
        + "\n"
        + toctree
    )


def model_page(entry: ModelEntry) -> str:
    """A per-model page that includes the model's own README verbatim."""
    return (
        f"(model-zoo-{entry.slug})=\n\n"
        f"{GENERATED_BY}\n\n"
        f"```{{include}} {README_PREFIX}/{entry.slug}/README.md\n"
        f"```\n"
    )


def pages_for(entry: ModelEntry, status: dict | None = None) -> dict[Path, str]:
    """The generated files owned by one model, mapped to their intended content."""
    records = (status if status is not None else read_status()).get("models", {})
    return {
        MODELS_DIR / f"{entry.slug}.md": model_page(entry),
        BADGES_DIR / f"{entry.slug}.json": json.dumps(
            badge(records.get(entry.slug, {})), indent=2
        )
        + "\n",
    }


def all_files(entries: list[ModelEntry], status: dict | None = None) -> dict[Path, str]:
    """Every file this module owns, mapped to its intended content."""
    status = status if status is not None else read_status()
    files = {DOCS_DIR / "index.md": index_page(entries, status)}
    for entry in entries:
        files.update(pages_for(entry, status))
    return files


def stale(files: dict[Path, str]) -> list[Path]:
    """Generated files left behind by a model that no longer exists."""
    return [
        path
        for path in sorted([*MODELS_DIR.glob("*.md"), *BADGES_DIR.glob("*.json")])
        if path not in files
    ]
