#
# Root of the pybamm module.
# Provides access to all shared functionality (models, solvers, etc.).
#
# The code in this file is adapted from Pints
# (see https://github.com/pints-team/pints)
#
import sys
import os


#
# Version info
#
from pybamm.version import __version__

#
# Constants
#
# Float format: a float can be converted to a 17 digit decimal and back without
# loss of information
FLOAT_FORMAT = "{: .17e}"
# Absolute path to the PyBaMM repo
script_path = os.path.abspath(__file__)

from .util import root_dir

ABSOLUTE_PATH = root_dir()
PARAMETER_PATH = [
    root_dir(),
    os.getcwd(),
    os.path.join(root_dir(), "pybamm", "input", "parameters"),
]

from .util import Timer, TimerTime, FuzzyDict, have_jax
from .logger import logger, set_logging_level, get_new_logger
from .settings import settings
from .citations import Citations, citations, print_citations

from .models.base_model import BaseModel
from .geometry.battery_geometry import battery_geometry
from .models.full_battery_models.base_battery_model import (
    BaseBatteryModel,
    BatteryModelOptions,
)
from .expression_tree.symbol import Symbol
from .expression_tree import (SpatialOperator,
                              Concatenation,
                              is_scalar_zero,
                              is_scalar_one,
                              is_scalar_minus_one,
                              is_scalar_minus_one,
                              is_matrix_zero,
                              is_matrix_one,
                              is_matrix_minus_one,
                              Integral,
                              Function,
                              Array,
                            )
from .expression_tree import *
from .expression_tree.broadcasts import Broadcast
from .expression_tree.binary_operators import *
from .expression_tree.parameter import Parameter
from .parameters.geometric_parameters import geometric_parameters, GeometricParameters
from .expression_tree.averages import _BaseAverage

import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'batch_study',
        'callbacks',
        'discretisations',
        'doc_utils',
        'experiment',
        'expression_tree',
        'geometry',
        'input',
        'install_odes',
        'meshes',
        'models',
        'parameters',
        'parameters_cli',
        'plotting',
        'simulation',
        'solvers',
        'spatial_methods',
        'util',
        'version',
    },
    submod_attrs={
        'batch_study': [
            'BatchStudy',
        ],
        'callbacks': [
            'Callback',
            'CallbackList',
            'LoggingCallback',
            'callback_loop_decorator',
            'setup_callbacks',
        ],
        'discretisations': [
            'Discretisation',
            'discretisation',
            'has_bc_of_form',
        ],
        'doc_utils': [
            'copy_parameter_doc_from_parent',
            'doc_extend_parent',
        ],
        'experiment': [
            'BaseTermination',
            'CrateTermination',
            'CurrentTermination',
            'CustomTermination',
            'Experiment',
            'VoltageTermination',
            'c_rate',
            'current',
            'experiment',
            'power',
            'resistance',
            'rest',
            'step',
            'step_termination',
            'steps',
            'string',
            'voltage',
        ],
        'expression_tree': [
            'AbsoluteValue',
            'Addition',
            'Arcsinh',
            'Arctan',
            'Array',
            'BackwardIndefiniteIntegral',
            'BaseIndefiniteIntegral',
            'BinaryOperator',
            'BoundaryGradient',
            'BoundaryIntegral',
            'BoundaryMass',
            'BoundaryOperator',
            'BoundaryValue',
            'Broadcast',
            'CasadiConverter',
            'Ceiling',
            'Concatenation',
            'ConcatenationVariable',
            'Cos',
            'Cosh',
            'CustomPrint',
            'DOMAIN_LEVELS',
            'DefiniteIntegralVector',
            'DeltaFunction',
            'DiscretisationError',
            'Divergence',
            'Division',
            'DomainConcatenation',
            'DomainError',
            'Downwind',
            'EMPTY_DOMAINS',
            'EqualHeaviside',
            'Equality',
            'Erf',
            'EvaluateAt',
            'EvaluatorJax',
            'EvaluatorJaxJacobian',
            'EvaluatorJaxSensitivities',
            'EvaluatorPython',
            'Exp',
            'ExplicitTimeIntegral',
            'Floor',
            'FullBroadcast',
            'FullBroadcastToEdges',
            'Function',
            'FunctionParameter',
            'GREEK_LETTERS',
            'GeometryError',
            'Gradient',
            'GradientSquared',
            'IndefiniteIntegral',
            'IndependentVariable',
            'Index',
            'Inner',
            'InputParameter',
            'Integral',
            'Interpolant',
            'Jacobian',
            'JaxCooMatrix',
            'KNOWN_COORD_SYS',
            'Laplacian',
            'Latexify',
            'Log',
            'Mass',
            'Matrix',
            'MatrixMultiplication',
            'Max',
            'Maximum',
            'Min',
            'Minimum',
            'ModelError',
            'ModelWarning',
            'Modulo',
            'Multiplication',
            'Negate',
            'NotConstant',
            'NotEqualHeaviside',
            'NumpyConcatenation',
            'OptionError',
            'OptionWarning',
            'PRINT_NAME_OVERRIDES',
            'Parameter',
            'Power',
            'PrimaryBroadcast',
            'PrimaryBroadcastToEdges',
            'RAverage',
            'Scalar',
            'SecondaryBroadcast',
            'SecondaryBroadcastToEdges',
            'Serialise',
            'ShapeError',
            'Sign',
            'Sin',
            'Sinh',
            'SizeAverage',
            'SolverError',
            'SolverWarning',
            'SparseStack',
            'SpatialOperator',
            'SpatialVariable',
            'SpatialVariableEdge',
            'SpecificFunction',
            'Sqrt',
            'StateVector',
            'StateVectorBase',
            'StateVectorDot',
            'Subtraction',
            'Symbol',
            'SymbolUnpacker',
            'Tanh',
            'TertiaryBroadcast',
            'TertiaryBroadcastToEdges',
            'Time',
            'UnaryOperator',
            'Upwind',
            'UpwindDownwind',
            'Variable',
            'VariableBase',
            'VariableDot',
            'Vector',
            'XAverage',
            'YZAverage',
            'ZAverage',
            'add',
            'arcsinh',
            'arctan',
            'array',
            'averages',
            'binary_operators',
            'boundary_gradient',
            'boundary_value',
            'broadcasts',
            'concatenation',
            'concatenations',
            'convert_to_casadi',
            'cos',
            'cosh',
            'create_jax_coo_matrix',
            'create_object_of_size',
            'custom_print_func',
            'div',
            'divide',
            'domain_concatenation',
            'domain_size',
            'downwind',
            'erf',
            'erfc',
            'evaluate_for_shape_using_domain',
            'evaluate_python',
            'exceptions',
            'exp',
            'find_symbols',
            'full_like',
            'functions',
            'get_rng_min_max_name',
            'grad',
            'grad_squared',
            'id_to_python_variable',
            'independent_variable',
            'inner',
            'input_parameter',
            'interpolant',
            'intersect',
            'is_constant',
            'is_matrix_minus_one',
            'is_matrix_one',
            'is_matrix_x',
            'is_matrix_zero',
            'is_scalar',
            'is_scalar_minus_one',
            'is_scalar_one',
            'is_scalar_x',
            'is_scalar_zero',
            'jacobian',
            'laplacian',
            'latexify',
            'linspace',
            'log',
            'log10',
            'matmul',
            'matrix',
            'maximum',
            'meshgrid',
            'minimum',
            'multiply',
            'numpy_concatenation',
            'ones_like',
            'operations',
            'parameter',
            'prettify_print_name',
            'print_name',
            'printing',
            'r_average',
            'scalar',
            'sech',
            'serialise',
            'sigmoid',
            'sign',
            'simplified_concatenation',
            'simplified_domain_concatenation',
            'simplified_function',
            'simplified_numpy_concatenation',
            'simplified_power',
            'simplify_if_constant',
            'sin',
            'sinh',
            'size_average',
            'smooth_absolute_value',
            'smooth_max',
            'smooth_min',
            'softminus',
            'softplus',
            'source',
            'sqrt',
            'state_vector',
            'substrings',
            'subtract',
            'surf',
            'symbol',
            'sympy_overrides',
            't',
            'tanh',
            'to_python',
            'unary_operators',
            'unpack_symbols',
            'upwind',
            'variable',
            'vector',
            'x_average',
            'xyz_average',
            'yz_average',
            'z_average',
            'zeros_like',
        ],
        'geometry': [
            'Geometry',
            'R_n',
            'R_n_edge',
            'R_p',
            'R_p_edge',
            'geometry',
            'r_macro',
            'r_macro_edge',
            'r_n',
            'r_n_edge',
            'r_n_prim',
            'r_n_sec',
            'r_p',
            'r_p_edge',
            'r_p_prim',
            'r_p_sec',
            'standard_spatial_vars',
            'whole_cell',
            'x',
            'x_edge',
            'x_n',
            'x_n_edge',
            'x_p',
            'x_p_edge',
            'x_s',
            'x_s_edge',
            'y',
            'y_edge',
            'z',
            'z_edge',
        ],
        'input': [
            'Ai2020',
            'Chen2020',
            'Chen2020_composite',
            'Ecker2015',
            'Ecker2015_graphite_halfcell',
            'LFP_electrolyte_exchange_current_density_kashkooli2017',
            'LFP_ocp_Afshar2017',
            'MSMR_example_set',
            'Marquis2019',
            'Mohtat2020',
            'NCA_Kim2011',
            'NMC_diffusivity_PeymanMPM',
            'NMC_electrolyte_exchange_current_density_PeymanMPM',
            'NMC_entropic_change_PeymanMPM',
            'NMC_ocp_PeymanMPM',
            'OKane2022',
            'OKane2022_graphite_SiOx_halfcell',
            'ORegan2022',
            'Prada2013',
            'Ramadass2004',
            'SEI_limited_dead_lithium_OKane2022',
            'Sulzer2019',
            'Xu2019',
            'aluminium_heat_capacity_CRC',
            'c1',
            'c1_data',
            'conductivity_Gu1997',
            'copper_heat_capacity_CRC',
            'copper_thermal_conductivity_CRC',
            'cracking_rate_Ai2020',
            'dUdT',
            'dUdT_data',
            'darken_thermodynamic_factor_Chapman1968',
            'diffusivity_Gu1997',
            'dlnf_dlnc_Ai2020',
            'ecm',
            'electrolyte_TDF_EC_EMC_3_7_Landesfeind2019',
            'electrolyte_TDF_base_Landesfeind2019',
            'electrolyte_conductivity_Ai2020',
            'electrolyte_conductivity_Capiglia1999',
            'electrolyte_conductivity_EC_EMC_3_7_Landesfeind2019',
            'electrolyte_conductivity_Ecker2015',
            'electrolyte_conductivity_Kim2011',
            'electrolyte_conductivity_Nyman2008',
            'electrolyte_conductivity_Nyman2008_arrhenius',
            'electrolyte_conductivity_PeymanMPM',
            'electrolyte_conductivity_Prada2013',
            'electrolyte_conductivity_Ramadass2004',
            'electrolyte_conductivity_Valoen2005',
            'electrolyte_conductivity_base_Landesfeind2019',
            'electrolyte_diffusivity_Ai2020',
            'electrolyte_diffusivity_Capiglia1999',
            'electrolyte_diffusivity_EC_EMC_3_7_Landesfeind2019',
            'electrolyte_diffusivity_Ecker2015',
            'electrolyte_diffusivity_Kim2011',
            'electrolyte_diffusivity_Nyman2008',
            'electrolyte_diffusivity_Nyman2008_arrhenius',
            'electrolyte_diffusivity_PeymanMPM',
            'electrolyte_diffusivity_Ramadass2004',
            'electrolyte_diffusivity_Valoen2005',
            'electrolyte_diffusivity_base_Landesfeind2019',
            'electrolyte_transference_number_EC_EMC_3_7_Landesfeind2019',
            'electrolyte_transference_number_base_Landesfeind2019',
            'example_set',
            'get_parameter_values',
            'graphite_LGM50_diffusivity_Chen2020',
            'graphite_LGM50_diffusivity_ORegan2022',
            'graphite_LGM50_electrolyte_exchange_current_density_Chen2020',
            'graphite_LGM50_electrolyte_exchange_current_density_ORegan2022',
            'graphite_LGM50_entropic_change_ORegan2022',
            'graphite_LGM50_heat_capacity_ORegan2022',
            'graphite_LGM50_ocp_Chen2020',
            'graphite_LGM50_ocp_Chen2020_data',
            'graphite_LGM50_thermal_conductivity_ORegan2022',
            'graphite_cracking_rate_Ai2020',
            'graphite_diffusivity_Dualfoil1998',
            'graphite_diffusivity_Ecker2015',
            'graphite_diffusivity_Kim2011',
            'graphite_diffusivity_PeymanMPM',
            'graphite_electrolyte_exchange_current_density_Dualfoil1998',
            'graphite_electrolyte_exchange_current_density_Ecker2015',
            'graphite_electrolyte_exchange_current_density_Kim2011',
            'graphite_electrolyte_exchange_current_density_PeymanMPM',
            'graphite_electrolyte_exchange_current_density_Ramadass2004',
            'graphite_entropic_change_Moura2016',
            'graphite_entropic_change_PeymanMPM',
            'graphite_entropy_Enertech_Ai2020_function',
            'graphite_mcmb2528_diffusivity_Dualfoil1998',
            'graphite_mcmb2528_ocp_Dualfoil1998',
            'graphite_ocp_Ecker2015',
            'graphite_ocp_Enertech_Ai2020',
            'graphite_ocp_Enertech_Ai2020_data',
            'graphite_ocp_Kim2011',
            'graphite_ocp_PeymanMPM',
            'graphite_ocp_Ramadass2004',
            'graphite_volume_change_Ai2020',
            'lead_acid',
            'lead_dioxide_exchange_current_density_Sulzer2019',
            'lead_dioxide_ocp_Bode1977',
            'lead_exchange_current_density_Sulzer2019',
            'lead_ocp_Bode1977',
            'li_metal_electrolyte_exchange_current_density_Xu2019',
            'lico2_cracking_rate_Ai2020',
            'lico2_diffusivity_Dualfoil1998',
            'lico2_diffusivity_Ramadass2004',
            'lico2_electrolyte_exchange_current_density_Dualfoil1998',
            'lico2_electrolyte_exchange_current_density_Ramadass2004',
            'lico2_entropic_change_Ai2020_function',
            'lico2_entropic_change_Moura2016',
            'lico2_ocp_Ai2020',
            'lico2_ocp_Ai2020_data',
            'lico2_ocp_Dualfoil1998',
            'lico2_ocp_Ramadass2004',
            'lico2_volume_change_Ai2020',
            'lithium_ion',
            'nca_diffusivity_Kim2011',
            'nca_electrolyte_exchange_current_density_Kim2011',
            'nca_ocp_Kim2011',
            'nco_diffusivity_Ecker2015',
            'nco_electrolyte_exchange_current_density_Ecker2015',
            'nco_ocp_Ecker2015',
            'nmc_LGM50_diffusivity_Chen2020',
            'nmc_LGM50_diffusivity_ORegan2022',
            'nmc_LGM50_electrolyte_exchange_current_density_Chen2020',
            'nmc_LGM50_electrolyte_exchange_current_density_ORegan2022',
            'nmc_LGM50_electronic_conductivity_ORegan2022',
            'nmc_LGM50_entropic_change_ORegan2022',
            'nmc_LGM50_heat_capacity_ORegan2022',
            'nmc_LGM50_ocp_Chen2020',
            'nmc_LGM50_thermal_conductivity_ORegan2022',
            'nmc_electrolyte_exchange_current_density_Xu2019',
            'nmc_ocp_Xu2019',
            'ocv',
            'ocv_data',
            'oxygen_exchange_current_density_Sulzer2019',
            'parameters',
            'plating_exchange_current_density_OKane2020',
            'r0',
            'r0_data',
            'r1',
            'r1_data',
            'separator_LGM50_heat_capacity_ORegan2022',
            'silicon_LGM50_electrolyte_exchange_current_density_Chen2020',
            'silicon_ocp_delithiation_Mark2016',
            'silicon_ocp_lithiation_Mark2016',
            'stripping_exchange_current_density_OKane2020',
            'volume_change_Ai2020',
        ],
        'install_odes': [
            'NO_WGET',
            'SUNDIALS_VERSION',
            'download_extract_library',
            'install_sundials',
            'main',
            'update_LD_LIBRARY_PATH',
        ],
        'meshes': [
            'Chebyshev1DSubMesh',
            'Exponential1DSubMesh',
            'Mesh',
            'MeshGenerator',
            'ScikitChebyshev2DSubMesh',
            'ScikitExponential2DSubMesh',
            'ScikitSubMesh2D',
            'ScikitUniform2DSubMesh',
            'SpectralVolume1DSubMesh',
            'SubMesh',
            'SubMesh0D',
            'SubMesh1D',
            'Uniform1DSubMesh',
            'UserSupplied1DSubMesh',
            'UserSupplied2DSubMesh',
            'meshes',
            'one_dimensional_submeshes',
            'scikit_fem_submeshes',
            'zero_dimensional_submesh',
        ],
        'models': [
            'AlternativeEffectiveResistance2D',
            'AsymmetricButlerVolmer',
            'BaseBatteryModel',
            'BaseEffectiveResistance',
            'BaseElectrode',
            'BaseElectrolyteConductivity',
            'BaseElectrolyteDiffusion',
            'BaseInterface',
            'BaseKinetics',
            'BaseLeadingOrderSurfaceForm',
            'BaseMechanics',
            'BaseOpenCircuitPotential',
            'BaseParticle',
            'BasePlating',
            'BasePotentialPair',
            'BaseSubModel',
            'BaseThermal',
            'BaseThroughCellModel',
            'BaseTransverseModel',
            'BasicDFN',
            'BasicDFNComposite',
            'BasicDFNHalfCell',
            'BasicFull',
            'BasicSPM',
            'BatteryModelDomainOptions',
            'BatteryModelOptions',
            'BatteryModelPhaseOptions',
            'BoundaryConditionsDict',
            'Bruggeman',
            'CCCVFunctionControl',
            'Composite',
            'CompositeAlgebraic',
            'CompositeDifferential',
            'Constant',
            'ConstantConcentration',
            'ConstantSEI',
            'CrackPropagation',
            'CurrentCollector1D',
            'CurrentCollector2D',
            'CurrentDriven',
            'CurrentForInverseButlerVolmer',
            'CurrentForInverseButlerVolmerLithiumMetal',
            'CurrentSigmoidOpenCircuitPotential',
            'DFN',
            'DiffusionLimited',
            'EffectiveResistance',
            'ElectrodeSOHHalfCell',
            'ElectrodeSOHSolver',
            'EquationDict',
            'Event',
            'EventType',
            'Explicit',
            'ExplicitCurrentControl',
            'ExplicitPowerControl',
            'ExplicitResistanceControl',
            'FickianDiffusion',
            'ForwardTafel',
            'Full',
            'FullAlgebraic',
            'FullDifferential',
            'FunctionControl',
            'Integrated',
            'InverseButlerVolmer',
            'Isothermal',
            'LOQS',
            'LeadingOrder',
            'LeadingOrderAlgebraic',
            'LeadingOrderDifferential',
            'Linear',
            'LithiumMetalBaseModel',
            'LithiumMetalExplicit',
            'LithiumMetalSurfaceForm',
            'LossActiveMaterial',
            'Lumped',
            'MPM',
            'MSMR',
            'MSMRButlerVolmer',
            'MSMRDiffusion',
            'MSMROpenCircuitPotential',
            'Marcus',
            'MarcusHushChidsey',
            'NaturalNumberOption',
            'NewmanTobias',
            'NoConvection',
            'NoMechanics',
            'NoOxygen',
            'NoPlating',
            'NoReaction',
            'NoSEI',
            'OCVElement',
            'OneDimensionalX',
            'OperatingModes',
            'Plating',
            'PolynomialProfile',
            'PotentialPair1plus1D',
            'PotentialPair2plus1D',
            'PowerFunctionControl',
            'RCElement',
            'ReactionDriven',
            'ReactionDrivenODE',
            'ResistanceFunctionControl',
            'ResistorElement',
            'SEIGrowth',
            'SPM',
            'SPMe',
            'SingleOpenCircuitPotential',
            'SurfaceForm',
            'SwellingOnly',
            'SymmetricButlerVolmer',
            'ThermalSubModel',
            'Thevenin',
            'Total',
            'TotalConcentration',
            'TotalInterfacialCurrent',
            'TotalMainKinetics',
            'TotalSEI',
            'Uniform',
            'VoltageFunctionControl',
            'VoltageModel',
            'XAveragedPolynomialProfile',
            'Yang2017',
            'active_material',
            'base_active_material',
            'base_battery_model',
            'base_convection',
            'base_current_collector',
            'base_electrode',
            'base_electrolyte_conductivity',
            'base_electrolyte_diffusion',
            'base_external_circuit',
            'base_interface',
            'base_kinetics',
            'base_lead_acid_model',
            'base_lithium_ion_model',
            'base_mechanics',
            'base_model',
            'base_ocp',
            'base_ohm',
            'base_oxygen_diffusion',
            'base_particle',
            'base_plating',
            'base_porosity',
            'base_sei',
            'base_submodel',
            'base_thermal',
            'base_through_cell_convection',
            'base_transport_efficiency',
            'base_transverse_convection',
            'base_utilisation',
            'basic_dfn',
            'basic_dfn_composite',
            'basic_dfn_half_cell',
            'basic_full',
            'basic_spm',
            'bruggeman_transport_efficiency',
            'butler_volmer',
            'calculate_theoretical_energy',
            'composite_conductivity',
            'composite_ohm',
            'composite_surface_form_conductivity',
            'constant_active_material',
            'constant_concentration',
            'constant_porosity',
            'constant_sei',
            'constant_utilisation',
            'convection',
            'crack_propagation',
            'current_collector',
            'current_driven_utilisation',
            'current_sigmoid_ocp',
            'dfn',
            'diffusion_limited',
            'ecm_model_options',
            'effective_resistance_current_collector',
            'electrode',
            'electrode_soh',
            'electrode_soh_half_cell',
            'electrolyte_conductivity',
            'electrolyte_diffusion',
            'equivalent_circuit',
            'equivalent_circuit_elements',
            'event',
            'explicit_control_external_circuit',
            'explicit_convection',
            'explicit_surface_form_conductivity',
            'external_circuit',
            'fickian_diffusion',
            'find_symbol_in_dict',
            'find_symbol_in_model',
            'find_symbol_in_tree',
            'full',
            'full_battery_models',
            'full_conductivity',
            'full_convection',
            'full_diffusion',
            'full_ohm',
            'full_oxygen_diffusion',
            'full_surface_form_conductivity',
            'full_utilisation',
            'function_control_external_circuit',
            'get_initial_ocps',
            'get_initial_stoichiometries',
            'get_initial_stoichiometry_half_cell',
            'get_min_max_ocps',
            'get_min_max_stoichiometries',
            'homogeneous_current_collector',
            'integrated_conductivity',
            'interface',
            'interface_utilisation',
            'inverse_butler_volmer',
            'inverse_kinetics',
            'isothermal',
            'kinetics',
            'lead_acid',
            'leading_ohm',
            'leading_order_conductivity',
            'leading_order_diffusion',
            'leading_oxygen_diffusion',
            'leading_surface_form_conductivity',
            'li_metal',
            'linear',
            'lithium_ion',
            'lithium_plating',
            'load_model',
            'loqs',
            'loss_active_material',
            'lumped',
            'marcus',
            'mpm',
            'msmr',
            'msmr_butler_volmer',
            'msmr_diffusion',
            'msmr_ocp',
            'newman_tobias',
            'no_convection',
            'no_mechanics',
            'no_oxygen',
            'no_plating',
            'no_reaction',
            'no_sei',
            'ocv_element',
            'ohm',
            'open_circuit_potential',
            'oxygen_diffusion',
            'particle',
            'particle_mechanics',
            'plating',
            'polynomial_profile',
            'porosity',
            'potential_pair',
            'pouch_cell',
            'pouch_cell_1D_current_collectors',
            'pouch_cell_2D_current_collectors',
            'rc_element',
            'reaction_driven_porosity',
            'reaction_driven_porosity_ode',
            'represents_positive_integer',
            'resistor_element',
            'sei',
            'sei_growth',
            'single_ocp',
            'spm',
            'spme',
            'submodels',
            'surface_form_ohm',
            'surface_potential_form',
            'swelling_only',
            'tafel',
            'theoretical_energy_integral',
            'thermal',
            'thevenin',
            'through_cell',
            'total_active_material',
            'total_interfacial_current',
            'total_main_kinetics',
            'total_particle_concentration',
            'total_sei',
            'transport_efficiency',
            'transverse',
            'uniform_convection',
            'voltage_model',
            'x_averaged_polynomial_profile',
            'x_full',
        ],
        'parameters': [
            'BaseParameters',
            'Domain',
            'DomainGeometricParameters',
            'DomainLeadAcidParameters',
            'DomainLithiumIonParameters',
            'DomainThermalParameters',
            'EcmParameters',
            'ElectricalParameters',
            'F',
            'GeometricParameters',
            'LeadAcidParameters',
            'LithiumIonParameters',
            'NullParameters',
            'ParameterSets',
            'ParameterValues',
            'ParticleGeometricParameters',
            'ParticleLithiumIonParameters',
            'PhaseLeadAcidParameters',
            'R',
            'ThermalParameters',
            'base_parameters',
            'bpx',
            'cell',
            'constants',
            'ecm_parameters',
            'electrical_parameters',
            'electrolyte',
            'experiment',
            'geometric_parameters',
            'get_size_distribution_parameters',
            'k_b',
            'lead_acid_parameters',
            'lithium_ion_parameters',
            'lognormal',
            'negative_current_collector',
            'negative_electrode',
            'parameter_sets',
            'parameter_values',
            'positive_current_collector',
            'positive_electrode',
            'preamble',
            'process_1D_data',
            'process_2D_data',
            'process_2D_data_csv',
            'process_3D_data_csv',
            'process_parameter_data',
            'q_e',
            'separator',
            'size_distribution_parameters',
            'thermal_parameters',
        ],
        'parameters_cli': [
            'add_parameter',
            'edit_parameter',
            'raise_error',
            'remove_parameter',
        ],
        'plotting': [
            'LoopList',
            'QuickPlot',
            'QuickPlotAxes',
            'ax_max',
            'ax_min',
            'close_plots',
            'dynamic_plot',
            'plot',
            'plot2D',
            'plot_summary_variables',
            'plot_voltage_components',
            'quick_plot',
            'split_long_string',
        ],
        'simulation': [
            'Simulation',
            'is_notebook',
            'load_sim',
        ],
        'solvers': [
            'AlgebraicSolver',
            'BaseSolver',
            'CasadiAlgebraicSolver',
            'CasadiSolver',
            'DummySolver',
            'EmptySolution',
            'IDAKLUSolver',
            'JaxSolver',
            'LRUDict',
            'NumpyEncoder',
            'ProcessedVariable',
            'ProcessedVariableComputed',
            'ScikitsDaeSolver',
            'ScikitsOdeSolver',
            'ScipySolver',
            'Solution',
            'algebraic_solver',
            'base_solver',
            'c_solvers',
            'casadi_algebraic_solver',
            'casadi_solver',
            'dummy_solver',
            'have_idaklu',
            'have_scikits_odes',
            'idaklu_solver',
            'idaklu_spec',
            'jax_bdf_integrate',
            'jax_bdf_solver',
            'jax_solver',
            'lrudict',
            'make_cycle_solution',
            'process',
            'processed_variable',
            'processed_variable_computed',
            'scikits_dae_solver',
            'scikits_ode_solver',
            'scikits_odes_spec',
            'scipy_solver',
            'solution',
        ],
        'spatial_methods': [
            'FiniteVolume',
            'ScikitFiniteElement',
            'SpatialMethod',
            'SpectralVolume',
            'ZeroDimensionalSpatialMethod',
            'finite_volume',
            'scikit_finite_element',
            'spatial_method',
            'spectral_volume',
            'zero_dimensional_method',
        ],
        'util': [
            'FuzzyDict',
            'JAXLIB_VERSION',
            'JAX_VERSION',
            'Timer',
            'TimerTime',
            'get_git_commit_info',
            'get_parameters_filepath',
            'have_jax',
            'have_optional_dependency',
            'install_jax',
            'is_constant_and_can_evaluate',
            'is_jax_compatible',
            'load',
            'rmse',
            'root_dir',
        ],
    },
)

__all__ = ['ABSOLUTE_PATH', 'AbsoluteValue', 'Addition', 'Ai2020',
           'AlgebraicSolver', 'AlternativeEffectiveResistance2D', 'Arcsinh',
           'Arctan', 'Array', 'AsymmetricButlerVolmer',
           'BackwardIndefiniteIntegral', 'BaseBatteryModel',
           'BaseEffectiveResistance', 'BaseElectrode',
           'BaseElectrolyteConductivity', 'BaseElectrolyteDiffusion',
           'BaseIndefiniteIntegral', 'BaseInterface', 'BaseKinetics',
           'BaseLeadingOrderSurfaceForm', 'BaseMechanics',
           'BaseOpenCircuitPotential', 'BaseParameters', 'BaseParticle',
           'BasePlating', 'BasePotentialPair', 'BaseSolver', 'BaseSubModel',
           'BaseTermination', 'BaseThermal', 'BaseThroughCellModel',
           'BaseTransverseModel', 'BasicDFN', 'BasicDFNComposite',
           'BasicDFNHalfCell', 'BasicFull', 'BasicSPM', 'BatchStudy',
           'BatteryModelDomainOptions', 'BatteryModelOptions',
           'BatteryModelPhaseOptions', 'BinaryOperator',
           'BoundaryConditionsDict', 'BoundaryGradient', 'BoundaryIntegral',
           'BoundaryMass', 'BoundaryOperator', 'BoundaryValue', 'Broadcast',
           'Bruggeman', 'CCCVFunctionControl', 'Callback', 'CallbackList',
           'CasadiAlgebraicSolver', 'CasadiConverter', 'CasadiSolver',
           'Ceiling', 'Chebyshev1DSubMesh', 'Chen2020', 'Chen2020_composite',
           'Composite', 'CompositeAlgebraic',
           'CompositeDifferential', 'Concatenation', 'ConcatenationVariable',
           'Constant', 'ConstantConcentration', 'ConstantSEI', 'Cos', 'Cosh',
           'CrackPropagation', 'CrateTermination', 'CurrentCollector1D',
           'CurrentCollector2D', 'CurrentDriven',
           'CurrentForInverseButlerVolmer',
           'CurrentForInverseButlerVolmerLithiumMetal',
           'CurrentSigmoidOpenCircuitPotential', 'CurrentTermination',
           'CustomPrint', 'CustomTermination', 'DFN', 'DOMAIN_LEVELS',
           'DefiniteIntegralVector', 'DeltaFunction', 'DiffusionLimited',
           'Discretisation', 'DiscretisationError', 'Divergence', 'Division',
           'Domain', 'DomainConcatenation', 'DomainError',
           'DomainGeometricParameters', 'DomainLeadAcidParameters',
           'DomainLithiumIonParameters', 'DomainThermalParameters', 'Downwind',
           'DummySolver', 'EMPTY_DOMAINS', 'Ecker2015',
           'Ecker2015_graphite_halfcell', 'EcmParameters',
           'EffectiveResistance', 'ElectricalParameters',
           'ElectrodeSOHHalfCell', 'ElectrodeSOHSolver', 'EmptySolution',
           'EqualHeaviside', 'Equality', 'EquationDict', 'Erf', 'EvaluateAt',
           'EvaluatorJax', 'EvaluatorJaxJacobian', 'EvaluatorJaxSensitivities',
           'EvaluatorPython', 'Event', 'EventType', 'Exp', 'Experiment',
           'Explicit', 'ExplicitCurrentControl', 'ExplicitPowerControl',
           'ExplicitResistanceControl', 'ExplicitTimeIntegral',
           'Exponential1DSubMesh', 'F', 'FLOAT_FORMAT', 'FORMAT',
           'FickianDiffusion', 'FiniteVolume', 'Floor', 'ForwardTafel', 'Full',
           'FullAlgebraic', 'FullBroadcast', 'FullBroadcastToEdges',
           'FullDifferential', 'Function', 'FunctionControl',
           'FunctionParameter', 'FuzzyDict', 'GREEK_LETTERS',
           'GeometricParameters', 'Geometry', 'GeometryError', 'Gradient',
           'GradientSquared', 'IDAKLUSolver', 'IndefiniteIntegral',
           'IndependentVariable', 'Index', 'Inner', 'InputParameter',
           'Integral', 'Integrated', 'Interpolant', 'InverseButlerVolmer',
           'Isothermal', 'JAXLIB_VERSION', 'JAX_VERSION', 'Jacobian',
           'JaxCooMatrix', 'JaxSolver', 'KNOWN_COORD_SYS',
           'LFP_electrolyte_exchange_current_density_kashkooli2017',
           'LFP_ocp_Afshar2017', 'LOG_FORMATTER', 'LOQS', 'LRUDict',
           'Laplacian', 'Latexify', 'LeadAcidParameters', 'LeadingOrder',
           'LeadingOrderAlgebraic', 'LeadingOrderDifferential', 'Linear',
           'LithiumIonParameters', 'LithiumMetalBaseModel',
           'LithiumMetalExplicit', 'LithiumMetalSurfaceForm', 'Log',
           'LoggingCallback', 'LoopList', 'LossActiveMaterial', 'Lumped',
           'MPM', 'MSMR', 'MSMRButlerVolmer', 'MSMRDiffusion',
           'MSMROpenCircuitPotential', 'MSMR_example_set', 'Marcus',
           'MarcusHushChidsey', 'Marquis2019', 'Mass', 'Matrix',
           'MatrixMultiplication', 'Max', 'Maximum', 'Mesh', 'MeshGenerator',
           'Min', 'Minimum', 'ModelError', 'ModelWarning', 'Modulo',
           'Mohtat2020', 'Multiplication', 'NCA_Kim2011',
           'NMC_diffusivity_PeymanMPM',
           'NMC_electrolyte_exchange_current_density_PeymanMPM',
           'NMC_entropic_change_PeymanMPM', 'NMC_ocp_PeymanMPM', 'NO_WGET',
           'NaturalNumberOption', 'Negate', 'NewmanTobias', 'NoConvection',
           'NoMechanics', 'NoOxygen', 'NoPlating', 'NoReaction', 'NoSEI',
           'NotConstant', 'NotEqualHeaviside', 'NullParameters',
           'NumpyConcatenation', 'NumpyEncoder', 'OCVElement', 'OKane2022',
           'OKane2022_graphite_SiOx_halfcell', 'ORegan2022', 'OneDimensionalX',
           'OperatingModes', 'OptionError', 'OptionWarning', 'PARAMETER_PATH',
           'PRINT_NAME_OVERRIDES', 'Parameter', 'ParameterSets',
           'ParameterValues', 'ParticleGeometricParameters',
           'ParticleLithiumIonParameters', 'PhaseLeadAcidParameters',
           'Plating', 'PolynomialProfile', 'PotentialPair1plus1D',
           'PotentialPair2plus1D', 'Power', 'PowerFunctionControl',
           'Prada2013', 'PrimaryBroadcast', 'PrimaryBroadcastToEdges',
           'ProcessedVariable', 'ProcessedVariableComputed', 'QuickPlot',
           'QuickPlotAxes', 'R', 'RAverage', 'RCElement', 'R_n', 'R_n_edge',
           'R_p', 'R_p_edge', 'Ramadass2004', 'ReactionDriven',
           'ReactionDrivenODE', 'ResistanceFunctionControl', 'ResistorElement',
           'SEIGrowth', 'SEI_limited_dead_lithium_OKane2022', 'SPM', 'SPMe',
           'SUNDIALS_VERSION', 'Scalar', 'ScikitChebyshev2DSubMesh',
           'ScikitExponential2DSubMesh', 'ScikitFiniteElement',
           'ScikitSubMesh2D', 'ScikitUniform2DSubMesh', 'ScikitsDaeSolver',
           'ScikitsOdeSolver', 'ScipySolver', 'SecondaryBroadcast',
           'SecondaryBroadcastToEdges', 'Serialise', 'ShapeError',
           'Sign', 'Simulation', 'Sin', 'SingleOpenCircuitPotential', 'Sinh',
           'SizeAverage', 'Solution', 'SolverError', 'SolverWarning',
           'SparseStack', 'SpatialMethod', 'SpatialOperator',
           'SpatialVariable', 'SpatialVariableEdge', 'SpecificFunction',
           'SpectralVolume', 'SpectralVolume1DSubMesh', 'Sqrt', 'StateVector',
           'StateVectorBase', 'StateVectorDot', 'SubMesh', 'SubMesh0D',
           'SubMesh1D', 'Subtraction', 'Sulzer2019', 'SurfaceForm',
           'SwellingOnly', 'Symbol', 'SymbolUnpacker', 'SymmetricButlerVolmer',
           'Tanh', 'TertiaryBroadcast', 'TertiaryBroadcastToEdges',
           'ThermalParameters', 'ThermalSubModel', 'Thevenin', 'Time', 'Timer',
           'TimerTime', 'Total', 'TotalConcentration',
           'TotalInterfacialCurrent', 'TotalMainKinetics', 'TotalSEI',
           'UnaryOperator', 'Uniform', 'Uniform1DSubMesh', 'Upwind',
           'UpwindDownwind', 'UserSupplied1DSubMesh', 'UserSupplied2DSubMesh',
           'Variable', 'VariableBase', 'VariableDot', 'Vector',
           'VoltageFunctionControl', 'VoltageModel', 'VoltageTermination',
           'XAverage', 'XAveragedPolynomialProfile', 'Xu2019', 'YZAverage',
           'Yang2017', 'ZAverage', 'ZeroDimensionalSpatialMethod',
           'active_material', 'add', 'add_parameter', 'algebraic_solver',
           'aluminium_heat_capacity_CRC', 'arcsinh', 'arctan', 'array',
           'averages', 'ax_max', 'ax_min', 'base_active_material',
           'base_battery_model', 'base_convection', 'base_current_collector',
           'base_electrode', 'base_electrolyte_conductivity',
           'base_electrolyte_diffusion', 'base_external_circuit',
           'base_interface', 'base_kinetics', 'base_lead_acid_model',
           'base_lithium_ion_model', 'base_mechanics', 'base_model',
           'base_ocp', 'base_ohm', 'base_oxygen_diffusion', 'base_parameters',
           'base_particle', 'base_plating', 'base_porosity', 'base_sei',
           'base_solver', 'base_submodel', 'base_thermal',
           'base_through_cell_convection', 'base_transport_efficiency',
           'base_transverse_convection', 'base_utilisation', 'basic_dfn',
           'basic_dfn_composite', 'basic_dfn_half_cell', 'basic_full',
           'basic_spm', 'batch_study', 'binary_operators',
           'boundary_gradient', 'boundary_value', 'bpx', 'broadcasts',
           'bruggeman_transport_efficiency', 'butler_volmer', 'c1', 'c1_data',
           'c_rate', 'c_solvers', 'calculate_theoretical_energy',
           'callback_loop_decorator', 'callbacks', 'casadi_algebraic_solver',
           'casadi_solver', 'cell', 'close_plots',
           'composite_conductivity', 'composite_ohm',
           'composite_surface_form_conductivity', 'concatenation',
           'concatenations', 'conductivity_Gu1997', 'constant_active_material',
           'constant_concentration', 'constant_porosity', 'constant_sei',
           'constant_utilisation', 'constants', 'convection',
           'convert_to_casadi', 'copper_heat_capacity_CRC',
           'copper_thermal_conductivity_CRC', 'copy_parameter_doc_from_parent',
           'cos', 'cosh', 'crack_propagation', 'cracking_rate_Ai2020',
           'create_jax_coo_matrix', 'create_object_of_size', 'current',
           'current_collector', 'current_driven_utilisation',
           'current_sigmoid_ocp', 'custom_print_func', 'dUdT', 'dUdT_data',
           'darken_thermodynamic_factor_Chapman1968', 'dfn',
           'diffusion_limited', 'diffusivity_Gu1997', 'discretisation',
           'discretisations', 'div', 'divide', 'dlnf_dlnc_Ai2020',
           'doc_extend_parent', 'doc_utils', 'domain_concatenation',
           'domain_size', 'download_extract_library', 'downwind',
           'dummy_solver', 'dynamic_plot', 'ecm', 'ecm_model_options',
           'ecm_parameters', 'edit_parameter',
           'effective_resistance_current_collector', 'electrical_parameters',
           'electrode', 'electrode_soh', 'electrode_soh_half_cell',
           'electrolyte', 'electrolyte_TDF_EC_EMC_3_7_Landesfeind2019',
           'electrolyte_TDF_base_Landesfeind2019', 'electrolyte_conductivity',
           'electrolyte_conductivity_Ai2020',
           'electrolyte_conductivity_Capiglia1999',
           'electrolyte_conductivity_EC_EMC_3_7_Landesfeind2019',
           'electrolyte_conductivity_Ecker2015',
           'electrolyte_conductivity_Kim2011',
           'electrolyte_conductivity_Nyman2008',
           'electrolyte_conductivity_Nyman2008_arrhenius',
           'electrolyte_conductivity_PeymanMPM',
           'electrolyte_conductivity_Prada2013',
           'electrolyte_conductivity_Ramadass2004',
           'electrolyte_conductivity_Valoen2005',
           'electrolyte_conductivity_base_Landesfeind2019',
           'electrolyte_diffusion', 'electrolyte_diffusivity_Ai2020',
           'electrolyte_diffusivity_Capiglia1999',
           'electrolyte_diffusivity_EC_EMC_3_7_Landesfeind2019',
           'electrolyte_diffusivity_Ecker2015',
           'electrolyte_diffusivity_Kim2011',
           'electrolyte_diffusivity_Nyman2008',
           'electrolyte_diffusivity_Nyman2008_arrhenius',
           'electrolyte_diffusivity_PeymanMPM',
           'electrolyte_diffusivity_Ramadass2004',
           'electrolyte_diffusivity_Valoen2005',
           'electrolyte_diffusivity_base_Landesfeind2019',
           'electrolyte_transference_number_EC_EMC_3_7_Landesfeind2019',
           'electrolyte_transference_number_base_Landesfeind2019',
           'equivalent_circuit', 'equivalent_circuit_elements', 'erf', 'erfc',
           'evaluate_for_shape_using_domain', 'evaluate_python', 'event',
           'example_set', 'exceptions', 'exp', 'experiment',
           'explicit_control_external_circuit', 'explicit_convection',
           'explicit_surface_form_conductivity', 'expression_tree',
           'external_circuit', 'fickian_diffusion', 'find_symbol_in_dict',
           'find_symbol_in_model', 'find_symbol_in_tree', 'find_symbols',
           'finite_volume', 'full', 'full_battery_models', 'full_conductivity',
           'full_convection', 'full_diffusion', 'full_like', 'full_ohm',
           'full_oxygen_diffusion', 'full_surface_form_conductivity',
           'full_utilisation', 'function_control_external_circuit',
           'functions', 'geometric_parameters', 'geometry',
           'get_git_commit_info', 'get_initial_ocps',
           'get_initial_stoichiometries',
           'get_initial_stoichiometry_half_cell', 'get_log_level_func',
           'get_min_max_ocps', 'get_min_max_stoichiometries',
           'get_parameter_values', 'get_parameters_filepath',
           'get_rng_min_max_name', 'get_size_distribution_parameters', 'grad',
           'grad_squared', 'graphite_LGM50_diffusivity_Chen2020',
           'graphite_LGM50_diffusivity_ORegan2022',
           'graphite_LGM50_electrolyte_exchange_current_density_Chen2020',
           'graphite_LGM50_electrolyte_exchange_current_density_ORegan2022',
           'graphite_LGM50_entropic_change_ORegan2022',
           'graphite_LGM50_heat_capacity_ORegan2022',
           'graphite_LGM50_ocp_Chen2020', 'graphite_LGM50_ocp_Chen2020_data',
           'graphite_LGM50_thermal_conductivity_ORegan2022',
           'graphite_cracking_rate_Ai2020',
           'graphite_diffusivity_Dualfoil1998',
           'graphite_diffusivity_Ecker2015', 'graphite_diffusivity_Kim2011',
           'graphite_diffusivity_PeymanMPM',
           'graphite_electrolyte_exchange_current_density_Dualfoil1998',
           'graphite_electrolyte_exchange_current_density_Ecker2015',
           'graphite_electrolyte_exchange_current_density_Kim2011',
           'graphite_electrolyte_exchange_current_density_PeymanMPM',
           'graphite_electrolyte_exchange_current_density_Ramadass2004',
           'graphite_entropic_change_Moura2016',
           'graphite_entropic_change_PeymanMPM',
           'graphite_entropy_Enertech_Ai2020_function',
           'graphite_mcmb2528_diffusivity_Dualfoil1998',
           'graphite_mcmb2528_ocp_Dualfoil1998', 'graphite_ocp_Ecker2015',
           'graphite_ocp_Enertech_Ai2020', 'graphite_ocp_Enertech_Ai2020_data',
           'graphite_ocp_Kim2011', 'graphite_ocp_PeymanMPM',
           'graphite_ocp_Ramadass2004', 'graphite_volume_change_Ai2020',
           'has_bc_of_form', 'have_idaklu', 'have_jax',
           'have_optional_dependency', 'have_scikits_odes',
           'homogeneous_current_collector', 'id_to_python_variable',
           'idaklu_solver', 'idaklu_spec', 'independent_variable', 'inner',
           'input', 'input_parameter', 'install_jax', 'install_odes',
           'install_sundials', 'integrated_conductivity', 'interface',
           'interface_utilisation', 'interpolant', 'intersect',
           'inverse_butler_volmer', 'inverse_kinetics', 'is_constant',
           'is_constant_and_can_evaluate', 'is_jax_compatible',
           'is_matrix_minus_one', 'is_matrix_one', 'is_matrix_x',
           'is_matrix_zero', 'is_notebook', 'is_scalar', 'is_scalar_minus_one',
           'is_scalar_one', 'is_scalar_x', 'is_scalar_zero', 'isothermal',
           'jacobian', 'jax_bdf_integrate', 'jax_bdf_solver', 'jax_solver',
           'k_b', 'kinetics', 'laplacian', 'latexify',
           'lead_acid', 'lead_acid_parameters',
           'lead_dioxide_exchange_current_density_Sulzer2019',
           'lead_dioxide_ocp_Bode1977',
           'lead_exchange_current_density_Sulzer2019', 'lead_ocp_Bode1977',
           'leading_ohm', 'leading_order_conductivity',
           'leading_order_diffusion', 'leading_oxygen_diffusion',
           'leading_surface_form_conductivity', 'li_metal',
           'li_metal_electrolyte_exchange_current_density_Xu2019',
           'lico2_cracking_rate_Ai2020', 'lico2_diffusivity_Dualfoil1998',
           'lico2_diffusivity_Ramadass2004',
           'lico2_electrolyte_exchange_current_density_Dualfoil1998',
           'lico2_electrolyte_exchange_current_density_Ramadass2004',
           'lico2_entropic_change_Ai2020_function',
           'lico2_entropic_change_Moura2016', 'lico2_ocp_Ai2020',
           'lico2_ocp_Ai2020_data', 'lico2_ocp_Dualfoil1998',
           'lico2_ocp_Ramadass2004', 'lico2_volume_change_Ai2020', 'linear',
           'linspace', 'lithium_ion', 'lithium_ion_parameters',
           'lithium_plating', 'load', 'load_model', 'load_sim', 'log', 'log10',
           'lognormal', 'loqs', 'loss_active_material', 'lrudict',
           'lumped', 'main', 'make_cycle_solution', 'marcus', 'matmul',
           'matrix', 'maximum', 'meshes', 'meshgrid', 'minimum', 'models',
           'mpm', 'msmr', 'msmr_butler_volmer', 'msmr_diffusion', 'msmr_ocp',
           'multiply', 'nca_diffusivity_Kim2011',
           'nca_electrolyte_exchange_current_density_Kim2011',
           'nca_ocp_Kim2011', 'nco_diffusivity_Ecker2015',
           'nco_electrolyte_exchange_current_density_Ecker2015',
           'nco_ocp_Ecker2015', 'negative_current_collector',
           'negative_electrode', 'new_levels', 'newman_tobias',
           'nmc_LGM50_diffusivity_Chen2020',
           'nmc_LGM50_diffusivity_ORegan2022',
           'nmc_LGM50_electrolyte_exchange_current_density_Chen2020',
           'nmc_LGM50_electrolyte_exchange_current_density_ORegan2022',
           'nmc_LGM50_electronic_conductivity_ORegan2022',
           'nmc_LGM50_entropic_change_ORegan2022',
           'nmc_LGM50_heat_capacity_ORegan2022', 'nmc_LGM50_ocp_Chen2020',
           'nmc_LGM50_thermal_conductivity_ORegan2022',
           'nmc_electrolyte_exchange_current_density_Xu2019', 'nmc_ocp_Xu2019',
           'no_convection', 'no_mechanics', 'no_oxygen', 'no_plating',
           'no_reaction', 'no_sei', 'numpy_concatenation', 'ocv', 'ocv_data',
           'ocv_element', 'ohm', 'one_dimensional_submeshes', 'ones_like',
           'open_circuit_potential', 'operations', 'oxygen_diffusion',
           'oxygen_exchange_current_density_Sulzer2019', 'parameter',
           'parameter_sets', 'parameter_values', 'parameters',
           'parameters_cli', 'particle', 'particle_mechanics', 'plating',
           'plating_exchange_current_density_OKane2020', 'plot', 'plot2D',
           'plot_summary_variables', 'plot_voltage_components', 'plotting',
           'polynomial_profile', 'porosity', 'positive_current_collector',
           'positive_electrode', 'potential_pair', 'pouch_cell',
           'pouch_cell_1D_current_collectors',
           'pouch_cell_2D_current_collectors', 'power', 'preamble',
           'prettify_print_name', 'print_name', 'printing',
           'process', 'process_1D_data', 'process_2D_data',
           'process_2D_data_csv', 'process_3D_data_csv',
           'process_parameter_data', 'processed_variable',
           'processed_variable_computed', 'q_e', 'quick_plot', 'r0', 'r0_data',
           'r1', 'r1_data', 'r_average', 'r_macro', 'r_macro_edge', 'r_n',
           'r_n_edge', 'r_n_prim', 'r_n_sec', 'r_p', 'r_p_edge', 'r_p_prim',
           'r_p_sec', 'raise_error', 'rc_element', 'reaction_driven_porosity',
           'reaction_driven_porosity_ode', 'remove_parameter',
           'represents_positive_integer', 'resistance', 'resistor_element',
           'rest', 'rmse', 'root_dir', 'scalar', 'scikit_fem_submeshes',
           'scikit_finite_element', 'scikits_dae_solver', 'scikits_ode_solver',
           'scikits_odes_spec', 'scipy_solver', 'script_path', 'sech', 'sei',
           'sei_growth', 'separator',
           'separator_LGM50_heat_capacity_ORegan2022', 'serialise',
           'setup_callbacks', 'sigmoid', 'sign',
           'silicon_LGM50_electrolyte_exchange_current_density_Chen2020',
           'silicon_ocp_delithiation_Mark2016',
           'silicon_ocp_lithiation_Mark2016', 'simplified_concatenation',
           'simplified_domain_concatenation', 'simplified_function',
           'simplified_numpy_concatenation', 'simplified_power',
           'simplify_if_constant', 'simulation', 'sin', 'single_ocp', 'sinh',
           'size_average', 'size_distribution_parameters',
           'smooth_absolute_value', 'smooth_max', 'smooth_min', 'softminus',
           'softplus', 'solution', 'solvers', 'source', 'spatial_method',
           'spatial_methods', 'spectral_volume', 'split_long_string', 'spm',
           'spme', 'sqrt', 'standard_spatial_vars', 'state_vector', 'step',
           'step_termination', 'steps', 'string',
           'stripping_exchange_current_density_OKane2020', 'submodels',
           'substrings', 'subtract', 'surf', 'surface_form_ohm',
           'surface_potential_form', 'swelling_only', 'symbol',
           'sympy_overrides', 't', 'tafel', 'tanh',
           'theoretical_energy_integral', 'thermal', 'thermal_parameters',
           'thevenin', 'through_cell', 'to_python', 'total_active_material',
           'total_interfacial_current', 'total_main_kinetics',
           'total_particle_concentration', 'total_sei', 'transport_efficiency',
           'transverse', 'unary_operators', 'uniform_convection',
           'unpack_symbols', 'update_LD_LIBRARY_PATH', 'upwind', 'util',
           'variable', 'vector', 'version', 'voltage', 'voltage_model',
           'volume_change_Ai2020', 'whole_cell', 'x', 'x_average',
           'x_averaged_polynomial_profile', 'x_edge', 'x_full', 'x_n',
           'x_n_edge', 'x_p', 'x_p_edge', 'x_s', 'x_s_edge', 'xyz_average',
           'y', 'y_edge', 'yz_average', 'z', 'z_average', 'z_edge',
           'zero_dimensional_method', 'zero_dimensional_submesh', 'zeros_like']
