version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - htmlzip

# Set the version of Python and other tools you might need
build:
  apt_packages:
    - "graphviz"
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --unshallow
    pre_build:
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ $READTHEDOCS_OUTPUT/linkcheck
    post_build:
      - mkdir --parents $READTHEDOCS_OUTPUT/pdf/
      - python -m sphinx -T -E -b latex -d docs/_build/doctrees -D language=en docs docs/build/
      - cd docs/build/ && cat latexmkrc
      - cd docs/build/ && latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=pybamm -interaction=nonstopmode || true
      - test -f docs/build/pybamm.pdf && echo "pybamm.pdf exists. Copying source file to $READTHEDOCS_OUTPUT/pdf/."
      - cp "docs/build/pybamm.pdf" $READTHEDOCS_OUTPUT/pdf/

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all
<<<<<<< HEAD
        - sphinx-linkcheck

=======
>>>>>>> b676427021809d91facc01640870a75752b8b55b
