/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) test_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[6] = {1, 2, 0, 1, 1, 0};
static const casadi_int casadi_s3[7] = {1, 2, 0, 1, 2, 0, 0};

/* rhs_:(i0,i1,i2,i3[2])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #2: @0 = (@0*@1) */
  w0 *= w1;
  /* #3: @0 = (-@0) */
  w0 = (- w0 );
  /* #4: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rhs_(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rhs__alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rhs__init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rhs__free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rhs__checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rhs__release(int mem) {
}

CASADI_SYMBOL_EXPORT void rhs__incref(void) {
}

CASADI_SYMBOL_EXPORT void rhs__decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rhs__n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rhs__n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rhs__default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rhs__name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rhs__name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rhs__sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rhs__sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rhs__work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* alg_:(i0,i1,i2,i3[2])->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @0 = (@0-@1) */
  w0 -= w1;
  /* #3: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int alg_(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int alg__alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int alg__init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void alg__free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int alg__checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void alg__release(int mem) {
}

CASADI_SYMBOL_EXPORT void alg__incref(void) {
}

CASADI_SYMBOL_EXPORT void alg__decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int alg__n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int alg__n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real alg__default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* alg__name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* alg__name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* alg__sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* alg__sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int alg__work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* jac_rhs:(i0,i1,i2,i3[2])->(o0[1x2,1nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, *w2=w+2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #2: @2 = ones(2x1) */
  casadi_fill(w2, 2, 1.);
  /* #3: {@3, NULL} = vertsplit(@2) */
  w3 = w2[0];
  /* #4: @1 = (@1*@3) */
  w1 *= w3;
  /* #5: @1 = (-@1) */
  w1 = (- w1 );
  /* #6: (@0[0] = @1) */
  for (rr=(&w0)+0, ss=(&w1); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_rhs(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_rhs_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_rhs_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_rhs_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_rhs_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_rhs_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_rhs_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_rhs_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_rhs_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int jac_rhs_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_rhs_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_rhs_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_rhs_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_rhs_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_rhs_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_rhs_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}

/* jac_alg:(i0,i1,i2,i3[2])->(o0[1x2]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2;
  /* #0: @0 = zeros(2x1) */
  casadi_clear(w0, 2);
  /* #1: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #2: {@2, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #3: (@0[0] = @2) */
  for (rr=w0+0, ss=(&w2); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #4: @2 = ones(2x1,1nz) */
  w2 = 1.;
  /* #5: {NULL, @1} = vertsplit(@2) */
  w1 = w2;
  /* #6: @1 = (-@1) */
  w1 = (- w1 );
  /* #7: (@0[1] = @1) */
  for (rr=w0+1, ss=(&w1); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #8: output[0][0] = @0 */
  casadi_copy(w0, 2, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_alg(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_alg_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_alg_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_alg_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_alg_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_alg_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_alg_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_alg_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_alg_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int jac_alg_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_alg_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_alg_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_alg_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_alg_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_alg_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_alg_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* x0:(i0[2])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int x0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int x0_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int x0_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x0_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int x0_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x0_release(int mem) {
}

CASADI_SYMBOL_EXPORT void x0_incref(void) {
}

CASADI_SYMBOL_EXPORT void x0_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x0_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int x0_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real x0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* z0:(i0[2])->(o0) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0;
  /* #0: @0 = 1 */
  w0 = 1.;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int z0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int z0_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int z0_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void z0_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int z0_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void z0_release(int mem) {
}

CASADI_SYMBOL_EXPORT void z0_incref(void) {
}

CASADI_SYMBOL_EXPORT void z0_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int z0_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int z0_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real z0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* z0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* z0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* z0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* z0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int z0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* variables:(i0,i1,i2,i3[2])->(o0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @0 = (@0+@1) */
  w0 += w1;
  /* #3: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #4: @0 = (@0-@1) */
  w0 -= w1;
  /* #5: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int variables(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int variables_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int variables_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void variables_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int variables_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void variables_release(int mem) {
}

CASADI_SYMBOL_EXPORT void variables_incref(void) {
}

CASADI_SYMBOL_EXPORT void variables_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int variables_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int variables_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real variables_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* variables_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* variables_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* variables_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* variables_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int variables_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
