[tox]
envlist = {windows}-{tests,quick,dev},tests,quick,dev

[testenv]
platform = !windows: [linux,darwin]
           windows: win32
skipsdist = true
skip_install = flake8: true	     
usedevelop = true
passenv = !windows: SUNDIALS_INST
whitelist_externals = !windows: sh
setenv =
       !windows: SUNDIALS_INST = {env:SUNDIALS_INST:{homedir}/.local}
       !windows: LD_LIBRARY_PATH = {homedir}/.local/lib{:}{env:LD_LIBRARY_PATH:}
deps =
     dev-!windows: cmake
     dev: black
     dev: flake8
     dev,doctests: sphinx>=1.5
     dev,doctests: guzzle-sphinx-theme
     !windows: scikits.odes
     
commands =
	 tests: python run-tests.py --unit --folder all
	 quick: python run-tests.py --unit
	 examples: python run-tests.py --examples
	 dev-!windows: sh -c "echo export LD_LIBRARY_PATH={env:LD_LIBRARY_PATH} >> {envbindir}/activate"
	 doctests: python run-tests.py --doctest

[testenv:pybamm-requires]
platform = [linux,darwin]
skip_install = true
passenv = HOME
whitelist_externals = git
deps =
     wget
     cmake
commands =
         python {toxinidir}/scripts/install_KLU_Sundials.py
	 - git clone https://github.com/pybind/pybind11.git {toxinidir}/pybind11

[testenv:flake8]
skip_install = true
deps = flake8>=3
commands = python -m flake8

[testenv:coverage]
skip_install = true
deps = coverage
commands = python -m coverage run run-tests.py --nosub

[testenv:docs]
skipdist = false
usedevelop = false
skip_install = false
deps =
     sphinx>=1.5
     guzzle-sphinx-theme
     sphinx-autobuild
changedir = docs
commands = sphinx-autobuild -BqT . {envtmpdir}/html

[flake8]
max-line-length = 88
exclude=
    .git,
    problems,
    __init__.py,
    venv,
    bin,
    etc,
    lib,
    lib64,
    share,
    pyvenv.cfg,
    third-party,
    sundials-5.0.0,
    KLU_module_deps,
    pybind11,
ignore=
    # False positive for white space before ':' on list slice
    # black should format these correctly
    E203,

    # Block comment should start with '# '
    # Not if it's a commented out line
    E265,

    # Ambiguous variable names
    # It's absolutely fine to have i and I
    E741,

    # List comprehension redefines variable
    # Re-using throw-away variables like `i`, `x`, etc. is a Good Idea
    F812,

    # Blank line at end of file
    # This increases readability
    W391,

    # Line break before binary operator
    # This is now actually advised in pep8
    W503,

    # Line break after binary operator
    W504,

    # Invalid escape sequence
    # These happen all the time in latex parts of docstrings,
    # e.g. \sigma
    W605,

[coverage:run]
source = pybamm