import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'active_material',
        'base_submodel',
        'convection',
        'current_collector',
        'electrode',
        'electrolyte_conductivity',
        'electrolyte_diffusion',
        'equivalent_circuit_elements',
        'external_circuit',
        'interface',
        'oxygen_diffusion',
        'particle',
        'particle_mechanics',
        'porosity',
        'thermal',
        'transport_efficiency',
    },
    submod_attrs={
        'active_material': [
            'BaseModel',
            'Constant',
            'LossActiveMaterial',
            'Total',
            'base_active_material',
            'constant_active_material',
            'loss_active_material',
            'total_active_material',
        ],
        'base_submodel': [
            'BaseSubModel',
        ],
        'convection': [
            'BaseModel',
            'BaseThroughCellModel',
            'BaseTransverseModel',
            'Explicit',
            'Full',
            'NoConvection',
            'Uniform',
            'base_convection',
            'base_through_cell_convection',
            'base_transverse_convection',
            'explicit_convection',
            'full_convection',
            'no_convection',
            'through_cell',
            'transverse',
            'uniform_convection',
        ],
        'current_collector': [
            'AlternativeEffectiveResistance2D',
            'BaseEffectiveResistance',
            'BaseModel',
            'BasePotentialPair',
            'EffectiveResistance',
            'PotentialPair1plus1D',
            'PotentialPair2plus1D',
            'Uniform',
            'base_current_collector',
            'effective_resistance_current_collector',
            'homogeneous_current_collector',
            'potential_pair',
        ],
        'electrode': [
            'BaseElectrode',
            'BaseModel',
            'Composite',
            'Full',
            'LeadingOrder',
            'LithiumMetalBaseModel',
            'LithiumMetalExplicit',
            'LithiumMetalSurfaceForm',
            'SurfaceForm',
            'base_electrode',
            'base_ohm',
            'composite_ohm',
            'full_ohm',
            'leading_ohm',
            'li_metal',
            'ohm',
            'surface_form_ohm',
        ],
        'electrolyte_conductivity': [
            'BaseElectrolyteConductivity',
            'BaseLeadingOrderSurfaceForm',
            'BaseModel',
            'Composite',
            'CompositeAlgebraic',
            'CompositeDifferential',
            'Explicit',
            'Full',
            'FullAlgebraic',
            'FullDifferential',
            'Integrated',
            'LeadingOrder',
            'LeadingOrderAlgebraic',
            'LeadingOrderDifferential',
            'base_electrolyte_conductivity',
            'composite_conductivity',
            'composite_surface_form_conductivity',
            'explicit_surface_form_conductivity',
            'full_conductivity',
            'full_surface_form_conductivity',
            'integrated_conductivity',
            'leading_order_conductivity',
            'leading_surface_form_conductivity',
            'surface_potential_form',
        ],
        'electrolyte_diffusion': [
            'BaseElectrolyteDiffusion',
            'ConstantConcentration',
            'Full',
            'LeadingOrder',
            'base_electrolyte_diffusion',
            'constant_concentration',
            'full_diffusion',
            'leading_order_diffusion',
        ],
        'equivalent_circuit_elements': [
            'OCVElement',
            'RCElement',
            'ResistorElement',
            'ThermalSubModel',
            'VoltageModel',
            'ocv_element',
            'rc_element',
            'resistor_element',
            'thermal',
            'voltage_model',
        ],
        'external_circuit': [
            'BaseModel',
            'CCCVFunctionControl',
            'ExplicitCurrentControl',
            'ExplicitPowerControl',
            'ExplicitResistanceControl',
            'FunctionControl',
            'PowerFunctionControl',
            'ResistanceFunctionControl',
            'VoltageFunctionControl',
            'base_external_circuit',
            'explicit_control_external_circuit',
            'function_control_external_circuit',
        ],
        'interface': [
            'AsymmetricButlerVolmer',
            'BaseInterface',
            'BaseKinetics',
            'BaseModel',
            'BaseOpenCircuitPotential',
            'BasePlating',
            'Constant',
            'ConstantSEI',
            'CurrentDriven',
            'CurrentForInverseButlerVolmer',
            'CurrentForInverseButlerVolmerLithiumMetal',
            'CurrentSigmoidOpenCircuitPotential',
            'DiffusionLimited',
            'ForwardTafel',
            'Full',
            'InverseButlerVolmer',
            'Linear',
            'MSMRButlerVolmer',
            'MSMROpenCircuitPotential',
            'Marcus',
            'MarcusHushChidsey',
            'NoPlating',
            'NoReaction',
            'NoSEI',
            'Plating',
            'SEIGrowth',
            'SingleOpenCircuitPotential',
            'SymmetricButlerVolmer',
            'TotalInterfacialCurrent',
            'TotalMainKinetics',
            'TotalSEI',
            'base_interface',
            'base_kinetics',
            'base_ocp',
            'base_plating',
            'base_sei',
            'base_utilisation',
            'butler_volmer',
            'constant_sei',
            'constant_utilisation',
            'current_driven_utilisation',
            'current_sigmoid_ocp',
            'diffusion_limited',
            'full_utilisation',
            'interface_utilisation',
            'inverse_butler_volmer',
            'inverse_kinetics',
            'kinetics',
            'linear',
            'lithium_plating',
            'marcus',
            'msmr_butler_volmer',
            'msmr_ocp',
            'no_plating',
            'no_reaction',
            'no_sei',
            'open_circuit_potential',
            'plating',
            'sei',
            'sei_growth',
            'single_ocp',
            'tafel',
            'total_interfacial_current',
            'total_main_kinetics',
            'total_sei',
        ],
        'oxygen_diffusion': [
            'BaseModel',
            'Full',
            'LeadingOrder',
            'NoOxygen',
            'base_oxygen_diffusion',
            'full_oxygen_diffusion',
            'leading_oxygen_diffusion',
            'no_oxygen',
        ],
        'particle': [
            'BaseParticle',
            'FickianDiffusion',
            'MSMRDiffusion',
            'PolynomialProfile',
            'TotalConcentration',
            'XAveragedPolynomialProfile',
            'base_particle',
            'fickian_diffusion',
            'msmr_diffusion',
            'polynomial_profile',
            'total_particle_concentration',
            'x_averaged_polynomial_profile',
        ],
        'particle_mechanics': [
            'BaseMechanics',
            'CrackPropagation',
            'NoMechanics',
            'SwellingOnly',
            'base_mechanics',
            'crack_propagation',
            'no_mechanics',
            'swelling_only',
        ],
        'porosity': [
            'BaseModel',
            'Constant',
            'ReactionDriven',
            'ReactionDrivenODE',
            'base_porosity',
            'constant_porosity',
            'reaction_driven_porosity',
            'reaction_driven_porosity_ode',
        ],
        'thermal': [
            'BaseThermal',
            'CurrentCollector1D',
            'CurrentCollector2D',
            'Isothermal',
            'Lumped',
            'OneDimensionalX',
            'base_thermal',
            'isothermal',
            'lumped',
            'pouch_cell',
            'pouch_cell_1D_current_collectors',
            'pouch_cell_2D_current_collectors',
            'x_full',
        ],
        'transport_efficiency': [
            'BaseModel',
            'Bruggeman',
            'base_transport_efficiency',
            'bruggeman_transport_efficiency',
        ],
    },
)

__all__ = ['AlternativeEffectiveResistance2D', 'AsymmetricButlerVolmer',
           'BaseEffectiveResistance', 'BaseElectrode',
           'BaseElectrolyteConductivity', 'BaseElectrolyteDiffusion',
           'BaseInterface', 'BaseKinetics', 'BaseLeadingOrderSurfaceForm',
           'BaseMechanics', 'BaseModel', 'BaseOpenCircuitPotential',
           'BaseParticle', 'BasePlating', 'BasePotentialPair', 'BaseSubModel',
           'BaseThermal', 'BaseThroughCellModel', 'BaseTransverseModel',
           'Bruggeman', 'CCCVFunctionControl', 'Composite',
           'CompositeAlgebraic', 'CompositeDifferential', 'Constant',
           'ConstantConcentration', 'ConstantSEI', 'CrackPropagation',
           'CurrentCollector1D', 'CurrentCollector2D', 'CurrentDriven',
           'CurrentForInverseButlerVolmer',
           'CurrentForInverseButlerVolmerLithiumMetal',
           'CurrentSigmoidOpenCircuitPotential', 'DiffusionLimited',
           'EffectiveResistance', 'Explicit', 'ExplicitCurrentControl',
           'ExplicitPowerControl', 'ExplicitResistanceControl',
           'FickianDiffusion', 'ForwardTafel', 'Full', 'FullAlgebraic',
           'FullDifferential', 'FunctionControl', 'Integrated',
           'InverseButlerVolmer', 'Isothermal', 'LeadingOrder',
           'LeadingOrderAlgebraic', 'LeadingOrderDifferential', 'Linear',
           'LithiumMetalBaseModel', 'LithiumMetalExplicit',
           'LithiumMetalSurfaceForm', 'LossActiveMaterial', 'Lumped',
           'MSMRButlerVolmer', 'MSMRDiffusion', 'MSMROpenCircuitPotential',
           'Marcus', 'MarcusHushChidsey', 'NoConvection', 'NoMechanics',
           'NoOxygen', 'NoPlating', 'NoReaction', 'NoSEI', 'OCVElement',
           'OneDimensionalX', 'Plating', 'PolynomialProfile',
           'PotentialPair1plus1D', 'PotentialPair2plus1D',
           'PowerFunctionControl', 'RCElement', 'ReactionDriven',
           'ReactionDrivenODE', 'ResistanceFunctionControl', 'ResistorElement',
           'SEIGrowth', 'SingleOpenCircuitPotential', 'SurfaceForm',
           'SwellingOnly', 'SymmetricButlerVolmer', 'ThermalSubModel', 'Total',
           'TotalConcentration', 'TotalInterfacialCurrent',
           'TotalMainKinetics', 'TotalSEI', 'Uniform',
           'VoltageFunctionControl', 'VoltageModel',
           'XAveragedPolynomialProfile', 'active_material',
           'base_active_material', 'base_convection', 'base_current_collector',
           'base_electrode', 'base_electrolyte_conductivity',
           'base_electrolyte_diffusion', 'base_external_circuit',
           'base_interface', 'base_kinetics', 'base_mechanics', 'base_ocp',
           'base_ohm', 'base_oxygen_diffusion', 'base_particle',
           'base_plating', 'base_porosity', 'base_sei', 'base_submodel',
           'base_thermal', 'base_through_cell_convection',
           'base_transport_efficiency', 'base_transverse_convection',
           'base_utilisation', 'bruggeman_transport_efficiency',
           'butler_volmer', 'composite_conductivity', 'composite_ohm',
           'composite_surface_form_conductivity', 'constant_active_material',
           'constant_concentration', 'constant_porosity', 'constant_sei',
           'constant_utilisation', 'convection', 'crack_propagation',
           'current_collector', 'current_driven_utilisation',
           'current_sigmoid_ocp', 'diffusion_limited',
           'effective_resistance_current_collector', 'electrode',
           'electrolyte_conductivity', 'electrolyte_diffusion',
           'equivalent_circuit_elements', 'explicit_control_external_circuit',
           'explicit_convection', 'explicit_surface_form_conductivity',
           'external_circuit', 'fickian_diffusion', 'full_conductivity',
           'full_convection', 'full_diffusion', 'full_ohm',
           'full_oxygen_diffusion', 'full_surface_form_conductivity',
           'full_utilisation', 'function_control_external_circuit',
           'homogeneous_current_collector', 'integrated_conductivity',
           'interface', 'interface_utilisation', 'inverse_butler_volmer',
           'inverse_kinetics', 'isothermal', 'kinetics', 'leading_ohm',
           'leading_order_conductivity', 'leading_order_diffusion',
           'leading_oxygen_diffusion', 'leading_surface_form_conductivity',
           'li_metal', 'linear', 'lithium_plating', 'loss_active_material',
           'lumped', 'marcus', 'msmr_butler_volmer', 'msmr_diffusion',
           'msmr_ocp', 'no_convection', 'no_mechanics', 'no_oxygen',
           'no_plating', 'no_reaction', 'no_sei', 'ocv_element', 'ohm',
           'open_circuit_potential', 'oxygen_diffusion', 'particle',
           'particle_mechanics', 'plating', 'polynomial_profile', 'porosity',
           'potential_pair', 'pouch_cell', 'pouch_cell_1D_current_collectors',
           'pouch_cell_2D_current_collectors', 'rc_element',
           'reaction_driven_porosity', 'reaction_driven_porosity_ode',
           'resistor_element', 'sei', 'sei_growth', 'single_ocp',
           'surface_form_ohm', 'surface_potential_form', 'swelling_only',
           'tafel', 'thermal', 'through_cell', 'total_active_material',
           'total_interfacial_current', 'total_main_kinetics',
           'total_particle_concentration', 'total_sei', 'transport_efficiency',
           'transverse', 'uniform_convection', 'voltage_model',
           'x_averaged_polynomial_profile', 'x_full']
