import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'base_battery_model',
        'equivalent_circuit',
        'lead_acid',
        'lithium_ion',
    },
    submod_attrs={
        'base_battery_model': [
            'BaseBatteryModel',
            'BatteryModelDomainOptions',
            'BatteryModelOptions',
            'BatteryModelPhaseOptions',
            'represents_positive_integer',
        ],
        'equivalent_circuit': [
            'NaturalNumberOption',
            'OperatingModes',
            'Thevenin',
            'ecm_model_options',
            'thevenin',
        ],
        'lead_acid': [
            'BaseModel',
            'BasicFull',
            'Full',
            'LOQS',
            'base_lead_acid_model',
            'basic_full',
            'full',
            'loqs',
        ],
        'lithium_ion': [
            'BaseModel',
            'BasicDFN',
            'BasicDFNComposite',
            'BasicDFNHalfCell',
            'BasicSPM',
            'DFN',
            'ElectrodeSOHHalfCell',
            'ElectrodeSOHSolver',
            'MPM',
            'MSMR',
            'NewmanTobias',
            'SPM',
            'SPMe',
            'Yang2017',
            'base_lithium_ion_model',
            'basic_dfn',
            'basic_dfn_composite',
            'basic_dfn_half_cell',
            'basic_spm',
            'calculate_theoretical_energy',
            'dfn',
            'electrode_soh',
            'electrode_soh_half_cell',
            'get_initial_ocps',
            'get_initial_stoichiometries',
            'get_initial_stoichiometry_half_cell',
            'get_min_max_ocps',
            'get_min_max_stoichiometries',
            'mpm',
            'msmr',
            'newman_tobias',
            'spm',
            'spme',
            'theoretical_energy_integral',
        ],
    },
)

__all__ = ['BaseBatteryModel', 'BaseModel', 'BasicDFN', 'BasicDFNComposite',
           'BasicDFNHalfCell', 'BasicFull', 'BasicSPM',
           'BatteryModelDomainOptions', 'BatteryModelOptions',
           'BatteryModelPhaseOptions', 'DFN', 'ElectrodeSOHHalfCell',
           'ElectrodeSOHSolver', 'Full', 'LOQS', 'MPM', 'MSMR',
           'NaturalNumberOption', 'NewmanTobias', 'OperatingModes', 'SPM',
           'SPMe', 'Thevenin', 'Yang2017', 'base_battery_model',
           'base_lead_acid_model', 'base_lithium_ion_model', 'basic_dfn',
           'basic_dfn_composite', 'basic_dfn_half_cell', 'basic_full',
           'basic_spm', 'calculate_theoretical_energy', 'dfn',
           'ecm_model_options', 'electrode_soh', 'electrode_soh_half_cell',
           'equivalent_circuit', 'full', 'get_initial_ocps',
           'get_initial_stoichiometries',
           'get_initial_stoichiometry_half_cell', 'get_min_max_ocps',
           'get_min_max_stoichiometries', 'lead_acid', 'lithium_ion', 'loqs',
           'mpm', 'msmr', 'newman_tobias', 'represents_positive_integer',
           'spm', 'spme', 'theoretical_energy_integral', 'thevenin']
