import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'array',
        'averages',
        'binary_operators',
        'broadcasts',
        'concatenations',
        'exceptions',
        'functions',
        'independent_variable',
        'input_parameter',
        'interpolant',
        'matrix',
        'operations',
        'parameter',
        'printing',
        'scalar',
        'state_vector',
        'symbol',
        'unary_operators',
        'variable',
        'vector',
    },
    submod_attrs={
        'array': [
            'Array',
            'linspace',
            'meshgrid',
        ],
        'averages': [
            'RAverage',
            'SizeAverage',
            'XAverage',
            'YZAverage',
            'ZAverage',
            'r_average',
            'size_average',
            'x_average',
            'xyz_average',
            'yz_average',
            'z_average',
        ],
        'binary_operators': [
            'Addition',
            'BinaryOperator',
            'Division',
            'EqualHeaviside',
            'Equality',
            'Inner',
            'MatrixMultiplication',
            'Maximum',
            'Minimum',
            'Modulo',
            'Multiplication',
            'NotEqualHeaviside',
            'Power',
            'Subtraction',
            'add',
            'divide',
            'inner',
            'matmul',
            'maximum',
            'minimum',
            'multiply',
            'sigmoid',
            'simplified_power',
            'smooth_max',
            'smooth_min',
            'softminus',
            'softplus',
            'source',
            'subtract',
        ],
        'broadcasts': [
            'Broadcast',
            'FullBroadcast',
            'FullBroadcastToEdges',
            'PrimaryBroadcast',
            'PrimaryBroadcastToEdges',
            'SecondaryBroadcast',
            'SecondaryBroadcastToEdges',
            'TertiaryBroadcast',
            'TertiaryBroadcastToEdges',
            'full_like',
            'ones_like',
            'zeros_like',
        ],
        'concatenations': [
            'Concatenation',
            'ConcatenationVariable',
            'DomainConcatenation',
            'NumpyConcatenation',
            'SparseStack',
            'concatenation',
            'domain_concatenation',
            'intersect',
            'numpy_concatenation',
            'simplified_concatenation',
            'simplified_domain_concatenation',
            'simplified_numpy_concatenation',
            'substrings',
        ],
        'exceptions': [
            'DiscretisationError',
            'DomainError',
            'GeometryError',
            'ModelError',
            'ModelWarning',
            'OptionError',
            'OptionWarning',
            'ShapeError',
            'SolverError',
            'SolverWarning',
        ],
        'functions': [
            'Arcsinh',
            'Arctan',
            'Cos',
            'Cosh',
            'Erf',
            'Exp',
            'Function',
            'Log',
            'Max',
            'Min',
            'Sin',
            'Sinh',
            'SpecificFunction',
            'Sqrt',
            'Tanh',
            'arcsinh',
            'arctan',
            'cos',
            'cosh',
            'erf',
            'erfc',
            'exp',
            'log',
            'log10',
            'sech',
            'simplified_function',
            'sin',
            'sinh',
            'sqrt',
            'tanh',
        ],
        'independent_variable': [
            'IndependentVariable',
            'KNOWN_COORD_SYS',
            'SpatialVariable',
            'SpatialVariableEdge',
            'Time',
            't',
        ],
        'input_parameter': [
            'InputParameter',
        ],
        'interpolant': [
            'Interpolant',
        ],
        'matrix': [
            'Matrix',
        ],
        'operations': [
            'CasadiConverter',
            'EvaluatorJax',
            'EvaluatorJaxJacobian',
            'EvaluatorJaxSensitivities',
            'EvaluatorPython',
            'Jacobian',
            'JaxCooMatrix',
            'Latexify',
            'Serialise',
            'SymbolUnpacker',
            'convert_to_casadi',
            'create_jax_coo_matrix',
            'evaluate_python',
            'find_symbols',
            'get_rng_min_max_name',
            'id_to_python_variable',
            'is_scalar',
            'jacobian',
            'latexify',
            'serialise',
            'to_python',
            'unpack_symbols',
        ],
        'parameter': [
            'FunctionParameter',
            'Parameter',
        ],
        'printing': [
            'CustomPrint',
            'GREEK_LETTERS',
            'PRINT_NAME_OVERRIDES',
            'custom_print_func',
            'prettify_print_name',
            'print_name',
            'sympy_overrides',
        ],
        'scalar': [
            'Scalar',
        ],
        'state_vector': [
            'StateVector',
            'StateVectorBase',
            'StateVectorDot',
        ],
        'symbol': [
            'DOMAIN_LEVELS',
            'EMPTY_DOMAINS',
            'Symbol',
            'create_object_of_size',
            'domain_size',
            'evaluate_for_shape_using_domain',
            'is_constant',
            'is_matrix_minus_one',
            'is_matrix_one',
            'is_matrix_x',
            'is_matrix_zero',
            'is_scalar_minus_one',
            'is_scalar_one',
            'is_scalar_x',
            'is_scalar_zero',
            'simplify_if_constant',
        ],
        'unary_operators': [
            'AbsoluteValue',
            'BackwardIndefiniteIntegral',
            'BaseIndefiniteIntegral',
            'BoundaryGradient',
            'BoundaryIntegral',
            'BoundaryMass',
            'BoundaryOperator',
            'BoundaryValue',
            'Ceiling',
            'DefiniteIntegralVector',
            'DeltaFunction',
            'Divergence',
            'Downwind',
            'EvaluateAt',
            'ExplicitTimeIntegral',
            'Floor',
            'Gradient',
            'GradientSquared',
            'IndefiniteIntegral',
            'Index',
            'Integral',
            'Laplacian',
            'Mass',
            'Negate',
            'NotConstant',
            'Sign',
            'SpatialOperator',
            'UnaryOperator',
            'Upwind',
            'UpwindDownwind',
            'boundary_gradient',
            'boundary_value',
            'div',
            'downwind',
            'grad',
            'grad_squared',
            'laplacian',
            'sign',
            'smooth_absolute_value',
            'surf',
            'upwind',
        ],
        'variable': [
            'Variable',
            'VariableBase',
            'VariableDot',
        ],
        'vector': [
            'Vector',
        ],
    },
)

__all__ = ['AbsoluteValue', 'Addition', 'Arcsinh', 'Arctan', 'Array',
           'BackwardIndefiniteIntegral', 'BaseIndefiniteIntegral',
           'BinaryOperator', 'BoundaryGradient', 'BoundaryIntegral',
           'BoundaryMass', 'BoundaryOperator', 'BoundaryValue', 'Broadcast',
           'CasadiConverter', 'Ceiling', 'Concatenation',
           'ConcatenationVariable', 'Cos', 'Cosh', 'CustomPrint',
           'DOMAIN_LEVELS', 'DefiniteIntegralVector', 'DeltaFunction',
           'DiscretisationError', 'Divergence', 'Division',
           'DomainConcatenation', 'DomainError', 'Downwind', 'EMPTY_DOMAINS',
           'EqualHeaviside', 'Equality', 'Erf', 'EvaluateAt', 'EvaluatorJax',
           'EvaluatorJaxJacobian', 'EvaluatorJaxSensitivities',
           'EvaluatorPython', 'Exp', 'ExplicitTimeIntegral', 'Floor',
           'FullBroadcast', 'FullBroadcastToEdges', 'Function',
           'FunctionParameter', 'GREEK_LETTERS', 'GeometryError', 'Gradient',
           'GradientSquared', 'IndefiniteIntegral', 'IndependentVariable',
           'Index', 'Inner', 'InputParameter', 'Integral', 'Interpolant',
           'Jacobian', 'JaxCooMatrix', 'KNOWN_COORD_SYS', 'Laplacian',
           'Latexify', 'Log', 'Mass', 'Matrix', 'MatrixMultiplication', 'Max',
           'Maximum', 'Min', 'Minimum', 'ModelError', 'ModelWarning', 'Modulo',
           'Multiplication', 'Negate', 'NotConstant', 'NotEqualHeaviside',
           'NumpyConcatenation', 'OptionError', 'OptionWarning',
           'PRINT_NAME_OVERRIDES', 'Parameter', 'Power', 'PrimaryBroadcast',
           'PrimaryBroadcastToEdges', 'RAverage', 'Scalar',
           'SecondaryBroadcast', 'SecondaryBroadcastToEdges', 'Serialise',
           'ShapeError', 'Sign', 'Sin', 'Sinh', 'SizeAverage', 'SolverError',
           'SolverWarning', 'SparseStack', 'SpatialOperator',
           'SpatialVariable', 'SpatialVariableEdge', 'SpecificFunction',
           'Sqrt', 'StateVector', 'StateVectorBase', 'StateVectorDot',
           'Subtraction', 'Symbol', 'SymbolUnpacker', 'Tanh',
           'TertiaryBroadcast', 'TertiaryBroadcastToEdges', 'Time',
           'UnaryOperator', 'Upwind', 'UpwindDownwind', 'Variable',
           'VariableBase', 'VariableDot', 'Vector', 'XAverage', 'YZAverage',
           'ZAverage', 'add', 'arcsinh', 'arctan', 'array', 'averages',
           'binary_operators', 'boundary_gradient', 'boundary_value',
           'broadcasts', 'concatenation', 'concatenations',
           'convert_to_casadi', 'cos', 'cosh', 'create_jax_coo_matrix',
           'create_object_of_size', 'custom_print_func', 'div', 'divide',
           'domain_concatenation', 'domain_size', 'downwind', 'erf', 'erfc',
           'evaluate_for_shape_using_domain', 'evaluate_python', 'exceptions',
           'exp', 'find_symbols', 'full_like', 'functions',
           'get_rng_min_max_name', 'grad', 'grad_squared',
           'id_to_python_variable', 'independent_variable', 'inner',
           'input_parameter', 'interpolant', 'intersect', 'is_constant',
           'is_matrix_minus_one', 'is_matrix_one', 'is_matrix_x',
           'is_matrix_zero', 'is_scalar', 'is_scalar_minus_one',
           'is_scalar_one', 'is_scalar_x', 'is_scalar_zero', 'jacobian',
           'laplacian', 'latexify', 'linspace', 'log', 'log10', 'matmul',
           'matrix', 'maximum', 'meshgrid', 'minimum', 'multiply',
           'numpy_concatenation', 'ones_like', 'operations', 'parameter',
           'prettify_print_name', 'print_name', 'printing', 'r_average',
           'scalar', 'sech', 'serialise', 'sigmoid', 'sign',
           'simplified_concatenation', 'simplified_domain_concatenation',
           'simplified_function', 'simplified_numpy_concatenation',
           'simplified_power', 'simplify_if_constant', 'sin', 'sinh',
           'size_average', 'smooth_absolute_value', 'smooth_max', 'smooth_min',
           'softminus', 'softplus', 'source', 'sqrt', 'state_vector',
           'substrings', 'subtract', 'surf', 'symbol', 'sympy_overrides', 't',
           'tanh', 'to_python', 'unary_operators', 'unpack_symbols', 'upwind',
           'variable', 'vector', 'x_average', 'xyz_average', 'yz_average',
           'z_average', 'zeros_like']
