import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'base_model',
        'event',
        'full_battery_models',
        'submodels',
    },
    submod_attrs={
        'base_model': [
            'BaseModel',
            'BoundaryConditionsDict',
            'EquationDict',
            'find_symbol_in_dict',
            'find_symbol_in_model',
            'find_symbol_in_tree',
            'load_model',
        ],
        'event': [
            'Event',
            'EventType',
        ],
        'full_battery_models': [
            'BaseBatteryModel',
            'BaseModel',
            'BasicDFN',
            'BasicDFNComposite',
            'BasicDFNHalfCell',
            'BasicFull',
            'BasicSPM',
            'BatteryModelDomainOptions',
            'BatteryModelOptions',
            'BatteryModelPhaseOptions',
            'DFN',
            'ElectrodeSOHHalfCell',
            'ElectrodeSOHSolver',
            'Full',
            'LOQS',
            'MPM',
            'MSMR',
            'NaturalNumberOption',
            'NewmanTobias',
            'OperatingModes',
            'SPM',
            'SPMe',
            'Thevenin',
            'Yang2017',
            'base_battery_model',
            'base_lead_acid_model',
            'base_lithium_ion_model',
            'basic_dfn',
            'basic_dfn_composite',
            'basic_dfn_half_cell',
            'basic_full',
            'basic_spm',
            'calculate_theoretical_energy',
            'dfn',
            'ecm_model_options',
            'electrode_soh',
            'electrode_soh_half_cell',
            'equivalent_circuit',
            'full',
            'get_initial_ocps',
            'get_initial_stoichiometries',
            'get_initial_stoichiometry_half_cell',
            'get_min_max_ocps',
            'get_min_max_stoichiometries',
            'lead_acid',
            'lithium_ion',
            'loqs',
            'mpm',
            'msmr',
            'newman_tobias',
            'represents_positive_integer',
            'spm',
            'spme',
            'theoretical_energy_integral',
            'thevenin',
        ],
        'submodels': [
            'AlternativeEffectiveResistance2D',
            'AsymmetricButlerVolmer',
            'BaseEffectiveResistance',
            'BaseElectrode',
            'BaseElectrolyteConductivity',
            'BaseElectrolyteDiffusion',
            'BaseInterface',
            'BaseKinetics',
            'BaseLeadingOrderSurfaceForm',
            'BaseMechanics',
            'BaseModel',
            'BaseOpenCircuitPotential',
            'BaseParticle',
            'BasePlating',
            'BasePotentialPair',
            'BaseSubModel',
            'BaseThermal',
            'BaseThroughCellModel',
            'BaseTransverseModel',
            'Bruggeman',
            'CCCVFunctionControl',
            'Composite',
            'CompositeAlgebraic',
            'CompositeDifferential',
            'Constant',
            'ConstantConcentration',
            'ConstantSEI',
            'CrackPropagation',
            'CurrentCollector1D',
            'CurrentCollector2D',
            'CurrentDriven',
            'CurrentForInverseButlerVolmer',
            'CurrentForInverseButlerVolmerLithiumMetal',
            'CurrentSigmoidOpenCircuitPotential',
            'DiffusionLimited',
            'EffectiveResistance',
            'Explicit',
            'ExplicitCurrentControl',
            'ExplicitPowerControl',
            'ExplicitResistanceControl',
            'FickianDiffusion',
            'ForwardTafel',
            'Full',
            'FullAlgebraic',
            'FullDifferential',
            'FunctionControl',
            'Integrated',
            'InverseButlerVolmer',
            'Isothermal',
            'LeadingOrder',
            'LeadingOrderAlgebraic',
            'LeadingOrderDifferential',
            'Linear',
            'LithiumMetalBaseModel',
            'LithiumMetalExplicit',
            'LithiumMetalSurfaceForm',
            'LossActiveMaterial',
            'Lumped',
            'MSMRButlerVolmer',
            'MSMRDiffusion',
            'MSMROpenCircuitPotential',
            'Marcus',
            'MarcusHushChidsey',
            'NoConvection',
            'NoMechanics',
            'NoOxygen',
            'NoPlating',
            'NoReaction',
            'NoSEI',
            'OCVElement',
            'OneDimensionalX',
            'Plating',
            'PolynomialProfile',
            'PotentialPair1plus1D',
            'PotentialPair2plus1D',
            'PowerFunctionControl',
            'RCElement',
            'ReactionDriven',
            'ReactionDrivenODE',
            'ResistanceFunctionControl',
            'ResistorElement',
            'SEIGrowth',
            'SingleOpenCircuitPotential',
            'SurfaceForm',
            'SwellingOnly',
            'SymmetricButlerVolmer',
            'ThermalSubModel',
            'Total',
            'TotalConcentration',
            'TotalInterfacialCurrent',
            'TotalMainKinetics',
            'TotalSEI',
            'Uniform',
            'VoltageFunctionControl',
            'VoltageModel',
            'XAveragedPolynomialProfile',
            'active_material',
            'base_active_material',
            'base_convection',
            'base_current_collector',
            'base_electrode',
            'base_electrolyte_conductivity',
            'base_electrolyte_diffusion',
            'base_external_circuit',
            'base_interface',
            'base_kinetics',
            'base_mechanics',
            'base_ocp',
            'base_ohm',
            'base_oxygen_diffusion',
            'base_particle',
            'base_plating',
            'base_porosity',
            'base_sei',
            'base_submodel',
            'base_thermal',
            'base_through_cell_convection',
            'base_transport_efficiency',
            'base_transverse_convection',
            'base_utilisation',
            'bruggeman_transport_efficiency',
            'butler_volmer',
            'composite_conductivity',
            'composite_ohm',
            'composite_surface_form_conductivity',
            'constant_active_material',
            'constant_concentration',
            'constant_porosity',
            'constant_sei',
            'constant_utilisation',
            'convection',
            'crack_propagation',
            'current_collector',
            'current_driven_utilisation',
            'current_sigmoid_ocp',
            'diffusion_limited',
            'effective_resistance_current_collector',
            'electrode',
            'electrolyte_conductivity',
            'electrolyte_diffusion',
            'equivalent_circuit_elements',
            'explicit_control_external_circuit',
            'explicit_convection',
            'explicit_surface_form_conductivity',
            'external_circuit',
            'fickian_diffusion',
            'full_conductivity',
            'full_convection',
            'full_diffusion',
            'full_ohm',
            'full_oxygen_diffusion',
            'full_surface_form_conductivity',
            'full_utilisation',
            'function_control_external_circuit',
            'homogeneous_current_collector',
            'integrated_conductivity',
            'interface',
            'interface_utilisation',
            'inverse_butler_volmer',
            'inverse_kinetics',
            'isothermal',
            'kinetics',
            'leading_ohm',
            'leading_order_conductivity',
            'leading_order_diffusion',
            'leading_oxygen_diffusion',
            'leading_surface_form_conductivity',
            'li_metal',
            'linear',
            'lithium_plating',
            'loss_active_material',
            'lumped',
            'marcus',
            'msmr_butler_volmer',
            'msmr_diffusion',
            'msmr_ocp',
            'no_convection',
            'no_mechanics',
            'no_oxygen',
            'no_plating',
            'no_reaction',
            'no_sei',
            'ocv_element',
            'ohm',
            'open_circuit_potential',
            'oxygen_diffusion',
            'particle',
            'particle_mechanics',
            'plating',
            'polynomial_profile',
            'porosity',
            'potential_pair',
            'pouch_cell',
            'pouch_cell_1D_current_collectors',
            'pouch_cell_2D_current_collectors',
            'rc_element',
            'reaction_driven_porosity',
            'reaction_driven_porosity_ode',
            'resistor_element',
            'sei',
            'sei_growth',
            'single_ocp',
            'surface_form_ohm',
            'surface_potential_form',
            'swelling_only',
            'tafel',
            'thermal',
            'through_cell',
            'total_active_material',
            'total_interfacial_current',
            'total_main_kinetics',
            'total_particle_concentration',
            'total_sei',
            'transport_efficiency',
            'transverse',
            'uniform_convection',
            'voltage_model',
            'x_averaged_polynomial_profile',
            'x_full',
        ],
    },
)

__all__ = ['AlternativeEffectiveResistance2D', 'AsymmetricButlerVolmer',
           'BaseBatteryModel', 'BaseEffectiveResistance', 'BaseElectrode',
           'BaseElectrolyteConductivity', 'BaseElectrolyteDiffusion',
           'BaseInterface', 'BaseKinetics', 'BaseLeadingOrderSurfaceForm',
           'BaseMechanics', 'BaseModel', 'BaseOpenCircuitPotential',
           'BaseParticle', 'BasePlating', 'BasePotentialPair', 'BaseSubModel',
           'BaseThermal', 'BaseThroughCellModel', 'BaseTransverseModel',
           'BasicDFN', 'BasicDFNComposite', 'BasicDFNHalfCell', 'BasicFull',
           'BasicSPM', 'BatteryModelDomainOptions', 'BatteryModelOptions',
           'BatteryModelPhaseOptions', 'BoundaryConditionsDict', 'Bruggeman',
           'CCCVFunctionControl', 'Composite', 'CompositeAlgebraic',
           'CompositeDifferential', 'Constant', 'ConstantConcentration',
           'ConstantSEI', 'CrackPropagation', 'CurrentCollector1D',
           'CurrentCollector2D', 'CurrentDriven',
           'CurrentForInverseButlerVolmer',
           'CurrentForInverseButlerVolmerLithiumMetal',
           'CurrentSigmoidOpenCircuitPotential', 'DFN', 'DiffusionLimited',
           'EffectiveResistance', 'ElectrodeSOHHalfCell', 'ElectrodeSOHSolver',
           'EquationDict', 'Event', 'EventType', 'Explicit',
           'ExplicitCurrentControl', 'ExplicitPowerControl',
           'ExplicitResistanceControl', 'FickianDiffusion', 'ForwardTafel',
           'Full', 'FullAlgebraic', 'FullDifferential', 'FunctionControl',
           'Integrated', 'InverseButlerVolmer', 'Isothermal', 'LOQS',
           'LeadingOrder', 'LeadingOrderAlgebraic', 'LeadingOrderDifferential',
           'Linear', 'LithiumMetalBaseModel', 'LithiumMetalExplicit',
           'LithiumMetalSurfaceForm', 'LossActiveMaterial', 'Lumped', 'MPM',
           'MSMR', 'MSMRButlerVolmer', 'MSMRDiffusion',
           'MSMROpenCircuitPotential', 'Marcus', 'MarcusHushChidsey',
           'NaturalNumberOption', 'NewmanTobias', 'NoConvection',
           'NoMechanics', 'NoOxygen', 'NoPlating', 'NoReaction', 'NoSEI',
           'OCVElement', 'OneDimensionalX', 'OperatingModes', 'Plating',
           'PolynomialProfile', 'PotentialPair1plus1D', 'PotentialPair2plus1D',
           'PowerFunctionControl', 'RCElement', 'ReactionDriven',
           'ReactionDrivenODE', 'ResistanceFunctionControl', 'ResistorElement',
           'SEIGrowth', 'SPM', 'SPMe', 'SingleOpenCircuitPotential',
           'SurfaceForm', 'SwellingOnly', 'SymmetricButlerVolmer',
           'ThermalSubModel', 'Thevenin', 'Total', 'TotalConcentration',
           'TotalInterfacialCurrent', 'TotalMainKinetics', 'TotalSEI',
           'Uniform', 'VoltageFunctionControl', 'VoltageModel',
           'XAveragedPolynomialProfile', 'Yang2017', 'active_material',
           'base_active_material', 'base_battery_model', 'base_convection',
           'base_current_collector', 'base_electrode',
           'base_electrolyte_conductivity', 'base_electrolyte_diffusion',
           'base_external_circuit', 'base_interface', 'base_kinetics',
           'base_lead_acid_model', 'base_lithium_ion_model', 'base_mechanics',
           'base_model', 'base_ocp', 'base_ohm', 'base_oxygen_diffusion',
           'base_particle', 'base_plating', 'base_porosity', 'base_sei',
           'base_submodel', 'base_thermal', 'base_through_cell_convection',
           'base_transport_efficiency', 'base_transverse_convection',
           'base_utilisation', 'basic_dfn', 'basic_dfn_composite',
           'basic_dfn_half_cell', 'basic_full', 'basic_spm',
           'bruggeman_transport_efficiency', 'butler_volmer',
           'calculate_theoretical_energy', 'composite_conductivity',
           'composite_ohm', 'composite_surface_form_conductivity',
           'constant_active_material', 'constant_concentration',
           'constant_porosity', 'constant_sei', 'constant_utilisation',
           'convection', 'crack_propagation', 'current_collector',
           'current_driven_utilisation', 'current_sigmoid_ocp', 'dfn',
           'diffusion_limited', 'ecm_model_options',
           'effective_resistance_current_collector', 'electrode',
           'electrode_soh', 'electrode_soh_half_cell',
           'electrolyte_conductivity', 'electrolyte_diffusion',
           'equivalent_circuit', 'equivalent_circuit_elements', 'event',
           'explicit_control_external_circuit', 'explicit_convection',
           'explicit_surface_form_conductivity', 'external_circuit',
           'fickian_diffusion', 'find_symbol_in_dict', 'find_symbol_in_model',
           'find_symbol_in_tree', 'full', 'full_battery_models',
           'full_conductivity', 'full_convection', 'full_diffusion',
           'full_ohm', 'full_oxygen_diffusion',
           'full_surface_form_conductivity', 'full_utilisation',
           'function_control_external_circuit', 'get_initial_ocps',
           'get_initial_stoichiometries',
           'get_initial_stoichiometry_half_cell', 'get_min_max_ocps',
           'get_min_max_stoichiometries', 'homogeneous_current_collector',
           'integrated_conductivity', 'interface', 'interface_utilisation',
           'inverse_butler_volmer', 'inverse_kinetics', 'isothermal',
           'kinetics', 'lead_acid', 'leading_ohm',
           'leading_order_conductivity', 'leading_order_diffusion',
           'leading_oxygen_diffusion', 'leading_surface_form_conductivity',
           'li_metal', 'linear', 'lithium_ion', 'lithium_plating',
           'load_model', 'loqs', 'loss_active_material', 'lumped', 'marcus',
           'mpm', 'msmr', 'msmr_butler_volmer', 'msmr_diffusion', 'msmr_ocp',
           'newman_tobias', 'no_convection', 'no_mechanics', 'no_oxygen',
           'no_plating', 'no_reaction', 'no_sei', 'ocv_element', 'ohm',
           'open_circuit_potential', 'oxygen_diffusion', 'particle',
           'particle_mechanics', 'plating', 'polynomial_profile', 'porosity',
           'potential_pair', 'pouch_cell', 'pouch_cell_1D_current_collectors',
           'pouch_cell_2D_current_collectors', 'rc_element',
           'reaction_driven_porosity', 'reaction_driven_porosity_ode',
           'represents_positive_integer', 'resistor_element', 'sei',
           'sei_growth', 'single_ocp', 'spm', 'spme', 'submodels',
           'surface_form_ohm', 'surface_potential_form', 'swelling_only',
           'tafel', 'theoretical_energy_integral', 'thermal', 'thevenin',
           'through_cell', 'total_active_material',
           'total_interfacial_current', 'total_main_kinetics',
           'total_particle_concentration', 'total_sei', 'transport_efficiency',
           'transverse', 'uniform_convection', 'voltage_model',
           'x_averaged_polynomial_profile', 'x_full']
