#!/usr/bin/env python
"""
Generate the __init__.pyi stub file for PyBaMM.

This script generates the stub file that enables:
1. IDE autocomplete for lazy-loaded attributes
2. Type checking support
3. lazy_loader integration for lazy imports

Usage:
    python scripts/generate_pyi_stub.py [options]

Options:
    --check     Don't write the file, just check if it would change (for CI)
    --validate  Validate that all configured imports exist in the modules

Examples:
    python scripts/generate_pyi_stub.py              # Generate/update stub
    python scripts/generate_pyi_stub.py --validate   # Validate imports exist
    python scripts/generate_pyi_stub.py --check      # CI check (exit 1 if outdated)
"""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

# Add src to path for imports
REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from pybamm._lazy_config import EAGER_IMPORTS, LAZY_IMPORTS, SUBMODULE_ALIASES


def generate_stub_content() -> str:
    """Generate the complete stub file content."""
    lines = [
        "# PyBaMM stub file for IDE support and type hints",
        "# Auto-generated by scripts/generate_pyi_stub.py - do not edit manually",
        "",
        "# Version",
        "from .version import __version__ as __version__",
        "",
        "# EAGERLY LOADED (imported at module load time)",
        "",
    ]

    # Eager imports
    for module_path, attrs in EAGER_IMPORTS.items():
        module_name = module_path.split(".")[-1]
        lines.append(f"# {module_name}")
        for attr in attrs:
            lines.append(f"from {module_path} import {attr} as {attr}")
        lines.append("")

    # Config module
    lines.append("# Config module")
    lines.append("from . import config as config")
    lines.append("")

    # Lazy imports
    lines.append("# LAZILY LOADED (via lazy_loader stub mechanism)")
    lines.append("")

    for module_path, attrs in LAZY_IMPORTS.items():
        module_name = module_path.split(".")[-1]
        lines.append(f"# {module_name}")
        for attr in attrs:
            lines.append(f"from {module_path} import {attr} as {attr}")
        lines.append("")

    # Submodule aliases
    lines.append("# SUBMODULE ALIASES")
    lines.append("")

    for alias, path in sorted(SUBMODULE_ALIASES.items()):
        parts = path.rsplit(".", 1)
        if len(parts) == 2 and parts[0]:
            parent_path, module_name = parts
            lines.append(f"from {parent_path} import {module_name} as {alias}")
        else:
            module_name = path.lstrip(".")
            lines.append(f"from . import {module_name} as {alias}")

    return "\n".join(lines) + "\n"


def validate_imports() -> list[str]:
    """Validate that all configured imports actually exist."""
    errors = []

    for label, imports in [("EAGER", EAGER_IMPORTS), ("LAZY", LAZY_IMPORTS)]:
        for module_path, attrs in imports.items():
            try:
                module = importlib.import_module(f"pybamm{module_path}")
                for attr in attrs:
                    if not hasattr(module, attr):
                        errors.append(f"{label}: {module_path}.{attr} not found")
            except ImportError as e:
                errors.append(f"{label}: Cannot import {module_path}: {e}")

    for alias, module_path in SUBMODULE_ALIASES.items():
        try:
            importlib.import_module(f"pybamm{module_path}")
        except ImportError as e:
            errors.append(f"SUBMODULE: {alias} -> {module_path}: {e}")

    return errors


def main():
    parser = argparse.ArgumentParser(
        description="Generate __init__.pyi stub file for PyBaMM"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if stub would change (for CI), exit 1 if different",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate that all configured imports exist",
    )
    args = parser.parse_args()

    stub_path = REPO_ROOT / "src" / "pybamm" / "__init__.pyi"

    if args.validate:
        print("Validating imports...")
        errors = validate_imports()
        if errors:
            print("Validation errors:")
            for error in errors:
                print(f"  - {error}")
            sys.exit(1)
        print("All imports validated successfully!")
        return

    content = generate_stub_content()

    if args.check:
        if stub_path.exists():
            existing = stub_path.read_text()
            if existing == content:
                print("Stub file is up to date.")
                sys.exit(0)
            else:
                print("Stub file is out of date. Run 'python scripts/generate_pyi_stub.py' to update.")
                sys.exit(1)
        else:
            print("Stub file does not exist.")
            sys.exit(1)

    stub_path.write_text(content)
    print(f"Generated {stub_path}")

    eager_count = sum(len(attrs) for attrs in EAGER_IMPORTS.values())
    lazy_count = sum(len(attrs) for attrs in LAZY_IMPORTS.values())
    submodule_count = len(SUBMODULE_ALIASES)
    print(f"  - {eager_count} eagerly loaded exports")
    print(f"  - {lazy_count} lazily loaded exports")
    print(f"  - {submodule_count} submodule aliases")
    print(f"  - Total: {eager_count + lazy_count + submodule_count} exports")


if __name__ == "__main__":
    main()
