"""Symbols pickled before symbols were slotted must keep loading.

The fixtures are trusted files generated by ``fixtures/legacy_pickle/generate.py``
against a pre-slot checkout.
"""

from __future__ import annotations

import gzip
import pathlib
import pickle

import numpy as np
from scipy.sparse import issparse

import pybamm

_FIX = pathlib.Path(__file__).parent / "fixtures" / "legacy_pickle"


def _load(name):
    with gzip.open(_FIX / name, "rb") as f:
        return pickle.load(f)  # nosec B301 - trusted, generated fixture


def _dense(value):
    return value.toarray() if issparse(value) else np.asarray(value)


class TestLegacyPickles:
    def test_every_symbol_class_loads(self):
        cases = _load("symbols.pkl.gz")
        assert len(cases) > 50
        for (class_name, _), case in cases.items():
            symbol = case["symbol"]
            assert type(symbol).__qualname__ == class_name
            assert {k: list(v) for k, v in symbol.domains.items()} == case["domains"]
            assert str(symbol) == case["str"]
            assert pybamm.replace(symbol, {}) is symbol
            if case["reference"] is not None:
                np.testing.assert_array_equal(
                    _dense(symbol.evaluate(t=10.0, y=case["y"], inputs={})),
                    _dense(case["reference"]),
                )

    def test_saved_simulation_solves_identically(self):
        sim = _load("spm_simulation.pkl.gz")
        times = np.linspace(0, 3600, 13)
        np.testing.assert_allclose(
            sim.solve([0, 3600])["Voltage [V]"](times),
            np.load(_FIX / "spm_voltage.npy"),
            rtol=1e-10,
            atol=0,
        )
