"""Symbols pickled before symbols were slotted must keep loading.

The fixtures are trusted files generated by ``fixtures/legacy_pickle/generate.py``
against a pre-slot checkout.
"""

from __future__ import annotations

import gzip
import json
import pathlib
import pickle

import numpy as np

import pybamm
from pybamm.expression_tree.operations.serialise import convert_symbol_to_json

_FIX = pathlib.Path(__file__).parent / "fixtures" / "legacy_pickle"


def _load(name):
    with gzip.open(_FIX / name, "rb") as f:
        return pickle.load(f)  # nosec B301 - trusted, generated fixture


class TestLegacyPickles:
    def test_every_symbol_class_loads(self):
        cases = _load("symbols.pkl.gz")
        assert len(cases) > 50
        for (class_name, _), case in cases.items():
            symbol = case["symbol"]
            assert type(symbol).__qualname__ == class_name
            assert {k: list(v) for k, v in symbol.domains.items()} == case["domains"]
            assert str(symbol) == case["str"]
            assert pybamm.replace(symbol, {}) is symbol
            # the whole tree, entries included, exactly as the pre-slot release wrote it
            assert json.dumps(convert_symbol_to_json(symbol)) == case["json"]

    def test_saved_simulation_solves_identically(self):
        sim = _load("spm_simulation.pkl.gz")
        times = np.linspace(0, 3600, 13)
        np.testing.assert_allclose(
            sim.solve([0, 3600])["Voltage [V]"](times),
            np.load(_FIX / "spm_voltage.npy"),
            rtol=1e-10,
            atol=0,
        )
