# PyBaMM stub file for IDE support and type hints
# This file is auto-generated by scripts/generate_pyi_stub.py
# Do not edit manually - regenerate with: python scripts/generate_pyi_stub.py
#
# This file enables:
# - IDE autocomplete for lazy-loaded attributes
# - Type checking support via mypy/pyright
# - lazy_loader integration for lazy imports

# Version
from .version import __version__ as __version__

# ============================================================================
# EAGERLY LOADED (imported at module load time)
# ============================================================================

# logger
from .logger import logger as logger
from .logger import set_logging_level as set_logging_level
from .logger import get_new_logger as get_new_logger

# settings
from .settings import settings as settings

# citations
from .citations import Citations as Citations
from .citations import citations as citations
from .citations import print_citations as print_citations

# symbol
from .expression_tree.symbol import Symbol as Symbol
from .expression_tree.symbol import domain_size as domain_size
from .expression_tree.symbol import create_object_of_size as create_object_of_size
from .expression_tree.symbol import (
    evaluate_for_shape_using_domain as evaluate_for_shape_using_domain,
)
from .expression_tree.symbol import is_constant as is_constant
from .expression_tree.symbol import is_scalar_zero as is_scalar_zero
from .expression_tree.symbol import is_scalar_one as is_scalar_one
from .expression_tree.symbol import is_scalar_minus_one as is_scalar_minus_one
from .expression_tree.symbol import is_matrix_zero as is_matrix_zero
from .expression_tree.symbol import is_matrix_one as is_matrix_one
from .expression_tree.symbol import is_matrix_minus_one as is_matrix_minus_one
from .expression_tree.symbol import simplify_if_constant as simplify_if_constant
from .expression_tree.symbol import convert_to_symbol as convert_to_symbol

# binary_operators
from .expression_tree.binary_operators import BinaryOperator as BinaryOperator
from .expression_tree.binary_operators import Power as Power
from .expression_tree.binary_operators import Addition as Addition
from .expression_tree.binary_operators import Subtraction as Subtraction
from .expression_tree.binary_operators import Multiplication as Multiplication
from .expression_tree.binary_operators import KroneckerProduct as KroneckerProduct
from .expression_tree.binary_operators import TensorProduct as TensorProduct
from .expression_tree.binary_operators import (
    MatrixMultiplication as MatrixMultiplication,
)
from .expression_tree.binary_operators import Division as Division
from .expression_tree.binary_operators import Inner as Inner
from .expression_tree.binary_operators import Equality as Equality
from .expression_tree.binary_operators import EqualHeaviside as EqualHeaviside
from .expression_tree.binary_operators import NotEqualHeaviside as NotEqualHeaviside
from .expression_tree.binary_operators import Modulo as Modulo
from .expression_tree.binary_operators import Minimum as Minimum
from .expression_tree.binary_operators import Maximum as Maximum
from .expression_tree.binary_operators import softplus as softplus
from .expression_tree.binary_operators import softminus as softminus
from .expression_tree.binary_operators import sigmoid as sigmoid
from .expression_tree.binary_operators import source as source

# concatenations
from .expression_tree.concatenations import Concatenation as Concatenation
from .expression_tree.concatenations import NumpyConcatenation as NumpyConcatenation
from .expression_tree.concatenations import DomainConcatenation as DomainConcatenation
from .expression_tree.concatenations import SparseStack as SparseStack
from .expression_tree.concatenations import (
    ConcatenationVariable as ConcatenationVariable,
)
from .expression_tree.concatenations import concatenation as concatenation
from .expression_tree.concatenations import numpy_concatenation as numpy_concatenation

# unary_operators
from .expression_tree.unary_operators import UnaryOperator as UnaryOperator
from .expression_tree.unary_operators import Negate as Negate
from .expression_tree.unary_operators import AbsoluteValue as AbsoluteValue
from .expression_tree.unary_operators import Transpose as Transpose
from .expression_tree.unary_operators import Sign as Sign
from .expression_tree.unary_operators import Floor as Floor
from .expression_tree.unary_operators import Ceiling as Ceiling
from .expression_tree.unary_operators import Index as Index
from .expression_tree.unary_operators import SpatialOperator as SpatialOperator
from .expression_tree.unary_operators import Gradient as Gradient
from .expression_tree.unary_operators import Divergence as Divergence
from .expression_tree.unary_operators import Laplacian as Laplacian
from .expression_tree.unary_operators import GradientSquared as GradientSquared
from .expression_tree.unary_operators import Mass as Mass
from .expression_tree.unary_operators import BoundaryMass as BoundaryMass
from .expression_tree.unary_operators import Integral as Integral
from .expression_tree.unary_operators import (
    BaseIndefiniteIntegral as BaseIndefiniteIntegral,
)
from .expression_tree.unary_operators import IndefiniteIntegral as IndefiniteIntegral
from .expression_tree.unary_operators import (
    BackwardIndefiniteIntegral as BackwardIndefiniteIntegral,
)
from .expression_tree.unary_operators import (
    DefiniteIntegralVector as DefiniteIntegralVector,
)
from .expression_tree.unary_operators import BoundaryIntegral as BoundaryIntegral
from .expression_tree.unary_operators import (
    OneDimensionalIntegral as OneDimensionalIntegral,
)
from .expression_tree.unary_operators import DeltaFunction as DeltaFunction
from .expression_tree.unary_operators import BoundaryOperator as BoundaryOperator
from .expression_tree.unary_operators import BoundaryValue as BoundaryValue
from .expression_tree.unary_operators import BoundaryMeshSize as BoundaryMeshSize
from .expression_tree.unary_operators import (
    ExplicitTimeIntegral as ExplicitTimeIntegral,
)
from .expression_tree.unary_operators import BoundaryGradient as BoundaryGradient
from .expression_tree.unary_operators import EvaluateAt as EvaluateAt
from .expression_tree.unary_operators import UpwindDownwind as UpwindDownwind
from .expression_tree.unary_operators import UpwindDownwind2D as UpwindDownwind2D
from .expression_tree.unary_operators import NodeToEdge2D as NodeToEdge2D
from .expression_tree.unary_operators import Magnitude as Magnitude
from .expression_tree.unary_operators import Upwind as Upwind
from .expression_tree.unary_operators import Downwind as Downwind
from .expression_tree.unary_operators import NotConstant as NotConstant
from .expression_tree.unary_operators import grad as grad
from .expression_tree.unary_operators import div as div
from .expression_tree.unary_operators import laplacian as laplacian
from .expression_tree.unary_operators import grad_squared as grad_squared
from .expression_tree.unary_operators import surf as surf
from .expression_tree.unary_operators import boundary_value as boundary_value
from .expression_tree.unary_operators import sign as sign
from .expression_tree.unary_operators import upwind as upwind
from .expression_tree.unary_operators import downwind as downwind

# averages
from .expression_tree.averages import _BaseAverage as _BaseAverage
from .expression_tree.averages import XAverage as XAverage
from .expression_tree.averages import YZAverage as YZAverage
from .expression_tree.averages import ZAverage as ZAverage
from .expression_tree.averages import RAverage as RAverage
from .expression_tree.averages import SizeAverage as SizeAverage
from .expression_tree.averages import x_average as x_average
from .expression_tree.averages import yz_average as yz_average
from .expression_tree.averages import z_average as z_average
from .expression_tree.averages import r_average as r_average
from .expression_tree.averages import size_average as size_average

# broadcasts
from .expression_tree.broadcasts import Broadcast as Broadcast
from .expression_tree.broadcasts import PrimaryBroadcast as PrimaryBroadcast
from .expression_tree.broadcasts import (
    PrimaryBroadcastToEdges as PrimaryBroadcastToEdges,
)
from .expression_tree.broadcasts import SecondaryBroadcast as SecondaryBroadcast
from .expression_tree.broadcasts import (
    SecondaryBroadcastToEdges as SecondaryBroadcastToEdges,
)
from .expression_tree.broadcasts import TertiaryBroadcast as TertiaryBroadcast
from .expression_tree.broadcasts import (
    TertiaryBroadcastToEdges as TertiaryBroadcastToEdges,
)
from .expression_tree.broadcasts import FullBroadcast as FullBroadcast
from .expression_tree.broadcasts import FullBroadcastToEdges as FullBroadcastToEdges
from .expression_tree.broadcasts import ones_like as ones_like
from .expression_tree.broadcasts import zeros_like as zeros_like

# functions
from .expression_tree.functions import Function as Function
from .expression_tree.functions import SpecificFunction as SpecificFunction
from .expression_tree.functions import Arcsinh as Arcsinh
from .expression_tree.functions import Arctan as Arctan
from .expression_tree.functions import Cos as Cos
from .expression_tree.functions import Cosh as Cosh
from .expression_tree.functions import Erf as Erf
from .expression_tree.functions import Exp as Exp
from .expression_tree.functions import Log as Log
from .expression_tree.functions import Max as Max
from .expression_tree.functions import Min as Min
from .expression_tree.functions import Sin as Sin
from .expression_tree.functions import Sinh as Sinh
from .expression_tree.functions import Sqrt as Sqrt
from .expression_tree.functions import Tanh as Tanh
from .expression_tree.functions import arcsinh as arcsinh
from .expression_tree.functions import arctan as arctan
from .expression_tree.functions import cos as cos
from .expression_tree.functions import cosh as cosh
from .expression_tree.functions import erf as erf
from .expression_tree.functions import exp as exp
from .expression_tree.functions import log as log
from .expression_tree.functions import log10 as log10
from .expression_tree.functions import max as max
from .expression_tree.functions import min as min
from .expression_tree.functions import sin as sin
from .expression_tree.functions import sinh as sinh
from .expression_tree.functions import sqrt as sqrt
from .expression_tree.functions import tanh as tanh

# interpolant
from .expression_tree.interpolant import Interpolant as Interpolant

# discrete_time_sum
from .expression_tree.discrete_time_sum import DiscreteTimeData as DiscreteTimeData
from .expression_tree.discrete_time_sum import DiscreteTimeSum as DiscreteTimeSum

# variable
from .expression_tree.variable import VariableBase as VariableBase
from .expression_tree.variable import Variable as Variable
from .expression_tree.variable import VariableDot as VariableDot

# coupled_variable
from .expression_tree.coupled_variable import CoupledVariable as CoupledVariable

# independent_variable
from .expression_tree.independent_variable import (
    IndependentVariable as IndependentVariable,
)
from .expression_tree.independent_variable import Time as Time
from .expression_tree.independent_variable import SpatialVariable as SpatialVariable
from .expression_tree.independent_variable import (
    SpatialVariableEdge as SpatialVariableEdge,
)
from .expression_tree.independent_variable import t as t
from .expression_tree.independent_variable import KNOWN_COORD_SYS as KNOWN_COORD_SYS

# exceptions
from .expression_tree.exceptions import DomainError as DomainError
from .expression_tree.exceptions import OptionError as OptionError
from .expression_tree.exceptions import OptionWarning as OptionWarning
from .expression_tree.exceptions import GeometryError as GeometryError
from .expression_tree.exceptions import ModelError as ModelError
from .expression_tree.exceptions import SolverError as SolverError
from .expression_tree.exceptions import SolverWarning as SolverWarning
from .expression_tree.exceptions import ShapeError as ShapeError
from .expression_tree.exceptions import ModelWarning as ModelWarning
from .expression_tree.exceptions import DiscretisationError as DiscretisationError
from .expression_tree.exceptions import InvalidModelJSONError as InvalidModelJSONError

# Config module
from . import config as config

# ============================================================================
# LAZILY LOADED (via lazy_loader stub mechanism)
# ============================================================================

# util
from .util import root_dir as root_dir
from .util import Timer as Timer
from .util import TimerTime as TimerTime
from .util import FuzzyDict as FuzzyDict
from .util import load as load
from .util import is_constant_and_can_evaluate as is_constant_and_can_evaluate
from .util import get_parameters_filepath as get_parameters_filepath
from .util import has_jax as has_jax
from .util import import_optional_dependency as import_optional_dependency

# array
from .expression_tree.array import Array as Array
from .expression_tree.array import linspace as linspace
from .expression_tree.array import meshgrid as meshgrid

# matrix
from .expression_tree.matrix import Matrix as Matrix

# vector
from .expression_tree.vector import Vector as Vector

# tensor_field
from .expression_tree.tensor_field import TensorField as TensorField

# vector_field
from .expression_tree.vector_field import VectorField as VectorField

# input_parameter
from .expression_tree.input_parameter import InputParameter as InputParameter

# parameter
from .expression_tree.parameter import Parameter as Parameter
from .expression_tree.parameter import FunctionParameter as FunctionParameter

# scalar
from .expression_tree.scalar import Scalar as Scalar
from .expression_tree.scalar import Constant as Constant

# state_vector
from .expression_tree.state_vector import StateVectorBase as StateVectorBase
from .expression_tree.state_vector import StateVector as StateVector
from .expression_tree.state_vector import StateVectorDot as StateVectorDot

# evaluate_python
from .expression_tree.operations.evaluate_python import find_symbols as find_symbols
from .expression_tree.operations.evaluate_python import (
    id_to_python_variable as id_to_python_variable,
)
from .expression_tree.operations.evaluate_python import to_python as to_python
from .expression_tree.operations.evaluate_python import (
    EvaluatorPython as EvaluatorPython,
)
from .expression_tree.operations.evaluate_python import EvaluatorJax as EvaluatorJax
from .expression_tree.operations.evaluate_python import JaxCooMatrix as JaxCooMatrix

# jacobian
from .expression_tree.operations.jacobian import Jacobian as Jacobian

# convert_to_casadi
from .expression_tree.operations.convert_to_casadi import (
    CasadiConverter as CasadiConverter,
)

# unpack_symbols
from .expression_tree.operations.unpack_symbols import SymbolUnpacker as SymbolUnpacker

# serialise
from .expression_tree.operations.serialise import Serialise as Serialise
from .expression_tree.operations.serialise import (
    ExpressionFunctionParameter as ExpressionFunctionParameter,
)

# base_model
from .models.base_model import BaseModel as BaseModel
from .models.base_model import ModelSolutionObservability as ModelSolutionObservability
from .models.base_model import load_model as load_model

# symbol_processor
from .models.symbol_processor import SymbolProcessor as SymbolProcessor

# event
from .models.event import Event as Event
from .models.event import EventType as EventType

# base_battery_model
from .models.full_battery_models.base_battery_model import (
    BaseBatteryModel as BaseBatteryModel,
)
from .models.full_battery_models.base_battery_model import (
    BatteryModelOptions as BatteryModelOptions,
)

# base_submodel
from .models.submodels.base_submodel import BaseSubModel as BaseSubModel

# geometry
from .geometry.geometry import Geometry as Geometry

# battery_geometry
from .geometry.battery_geometry import battery_geometry as battery_geometry

# parameter_values
from .parameters.parameter_values import ParameterValues as ParameterValues
from .parameters.parameter_values import scalarize_dict as scalarize_dict
from .parameters.parameter_values import arrayize_dict as arrayize_dict

# geometric_parameters
from .parameters.geometric_parameters import (
    geometric_parameters as geometric_parameters,
)
from .parameters.geometric_parameters import GeometricParameters as GeometricParameters

# electrical_parameters
from .parameters.electrical_parameters import (
    electrical_parameters as electrical_parameters,
)
from .parameters.electrical_parameters import (
    ElectricalParameters as ElectricalParameters,
)

# thermal_parameters
from .parameters.thermal_parameters import thermal_parameters as thermal_parameters
from .parameters.thermal_parameters import ThermalParameters as ThermalParameters

# lithium_ion_parameters
from .parameters.lithium_ion_parameters import (
    LithiumIonParameters as LithiumIonParameters,
)

# lead_acid_parameters
from .parameters.lead_acid_parameters import LeadAcidParameters as LeadAcidParameters

# ecm_parameters
from .parameters.ecm_parameters import EcmParameters as EcmParameters

# size_distribution_parameters
from .parameters.size_distribution_parameters import (
    get_size_distribution_parameters as get_size_distribution_parameters,
)
from .parameters.size_distribution_parameters import lognormal as lognormal

# discretisation
from .discretisations.discretisation import Discretisation as Discretisation
from .discretisations.discretisation import has_bc_of_form as has_bc_of_form

# meshes
from .meshes.meshes import Mesh as Mesh
from .meshes.meshes import SubMesh as SubMesh
from .meshes.meshes import MeshGenerator as MeshGenerator

# zero_dimensional_submesh
from .meshes.zero_dimensional_submesh import SubMesh0D as SubMesh0D

# one_dimensional_submeshes
from .meshes.one_dimensional_submeshes import SubMesh1D as SubMesh1D
from .meshes.one_dimensional_submeshes import Uniform1DSubMesh as Uniform1DSubMesh
from .meshes.one_dimensional_submeshes import (
    Exponential1DSubMesh as Exponential1DSubMesh,
)
from .meshes.one_dimensional_submeshes import Chebyshev1DSubMesh as Chebyshev1DSubMesh
from .meshes.one_dimensional_submeshes import (
    UserSupplied1DSubMesh as UserSupplied1DSubMesh,
)
from .meshes.one_dimensional_submeshes import (
    SpectralVolume1DSubMesh as SpectralVolume1DSubMesh,
)
from .meshes.one_dimensional_submeshes import (
    SymbolicUniform1DSubMesh as SymbolicUniform1DSubMesh,
)

# two_dimensional_submeshes
from .meshes.two_dimensional_submeshes import SubMesh2D as SubMesh2D
from .meshes.two_dimensional_submeshes import Uniform2DSubMesh as Uniform2DSubMesh

# scikit_fem_submeshes
from .meshes.scikit_fem_submeshes import ScikitSubMesh2D as ScikitSubMesh2D
from .meshes.scikit_fem_submeshes import (
    ScikitUniform2DSubMesh as ScikitUniform2DSubMesh,
)
from .meshes.scikit_fem_submeshes import (
    ScikitExponential2DSubMesh as ScikitExponential2DSubMesh,
)
from .meshes.scikit_fem_submeshes import (
    ScikitChebyshev2DSubMesh as ScikitChebyshev2DSubMesh,
)
from .meshes.scikit_fem_submeshes import UserSupplied2DSubMesh as UserSupplied2DSubMesh

# scikit_fem_submeshes_3d
from .meshes.scikit_fem_submeshes_3d import ScikitFemSubMesh3D as ScikitFemSubMesh3D
from .meshes.scikit_fem_submeshes_3d import ScikitFemGenerator3D as ScikitFemGenerator3D
from .meshes.scikit_fem_submeshes_3d import (
    UserSuppliedSubmesh3D as UserSuppliedSubmesh3D,
)

# spatial_method
from .spatial_methods.spatial_method import SpatialMethod as SpatialMethod

# zero_dimensional_method
from .spatial_methods.zero_dimensional_method import (
    ZeroDimensionalSpatialMethod as ZeroDimensionalSpatialMethod,
)

# finite_volume
from .spatial_methods.finite_volume import FiniteVolume as FiniteVolume

# finite_volume_2d
from .spatial_methods.finite_volume_2d import FiniteVolume2D as FiniteVolume2D

# spectral_volume
from .spatial_methods.spectral_volume import SpectralVolume as SpectralVolume

# scikit_finite_element
from .spatial_methods.scikit_finite_element import (
    ScikitFiniteElement as ScikitFiniteElement,
)

# scikit_finite_element_3d
from .spatial_methods.scikit_finite_element_3d import (
    ScikitFiniteElement3D as ScikitFiniteElement3D,
)

# solution
from .solvers.solution import Solution as Solution
from .solvers.solution import EmptySolution as EmptySolution
from .solvers.solution import make_cycle_solution as make_cycle_solution

# processed_variable_time_integral
from .solvers.processed_variable_time_integral import (
    ProcessedVariableTimeIntegral as ProcessedVariableTimeIntegral,
)

# processed_variable
from .solvers.processed_variable import ProcessedVariable as ProcessedVariable
from .solvers.processed_variable import ProcessedVariable2DFVM as ProcessedVariable2DFVM
from .solvers.processed_variable import process_variable as process_variable
from .solvers.processed_variable import (
    ProcessedVariableUnstructured as ProcessedVariableUnstructured,
)

# processed_variable_computed
from .solvers.processed_variable_computed import (
    ProcessedVariableComputed as ProcessedVariableComputed,
)

# summary_variable
from .solvers.summary_variable import SummaryVariables as SummaryVariables

# base_solver
from .solvers.base_solver import BaseSolver as BaseSolver

# dummy_solver
from .solvers.dummy_solver import DummySolver as DummySolver

# algebraic_solver
from .solvers.algebraic_solver import AlgebraicSolver as AlgebraicSolver

# casadi_solver
from .solvers.casadi_solver import CasadiSolver as CasadiSolver

# casadi_algebraic_solver
from .solvers.casadi_algebraic_solver import (
    CasadiAlgebraicSolver as CasadiAlgebraicSolver,
)

# scipy_solver
from .solvers.scipy_solver import ScipySolver as ScipySolver

# composite_solver
from .solvers.composite_solver import CompositeSolver as CompositeSolver

# jax_solver
from .solvers.jax_solver import JaxSolver as JaxSolver

# jax_bdf_solver
from .solvers.jax_bdf_solver import jax_bdf_integrate as jax_bdf_integrate

# idaklu_jax
from .solvers.idaklu_jax import IDAKLUJax as IDAKLUJax

# idaklu_solver
from .solvers.idaklu_solver import IDAKLUSolver as IDAKLUSolver

# experiment
from .experiment.experiment import Experiment as Experiment

# quick_plot
from .plotting.quick_plot import QuickPlot as QuickPlot
from .plotting.quick_plot import close_plots as close_plots
from .plotting.quick_plot import QuickPlotAxes as QuickPlotAxes

# plot
from .plotting.plot import plot as plot

# plot2D
from .plotting.plot2D import plot2D as plot2D

# plot_voltage_components
from .plotting.plot_voltage_components import (
    plot_voltage_components as plot_voltage_components,
)

# plot_thermal_components
from .plotting.plot_thermal_components import (
    plot_thermal_components as plot_thermal_components,
)

# plot_summary_variables
from .plotting.plot_summary_variables import (
    plot_summary_variables as plot_summary_variables,
)

# dynamic_plot
from .plotting.dynamic_plot import dynamic_plot as dynamic_plot

# plot_3d_cross_section
from .plotting.plot_3d_cross_section import (
    plot_3d_cross_section as plot_3d_cross_section,
)

# plot_3d_heatmap
from .plotting.plot_3d_heatmap import plot_3d_heatmap as plot_3d_heatmap

# simulation
from .simulation import Simulation as Simulation
from .simulation import load_sim as load_sim
from .simulation import is_notebook as is_notebook

# batch_study
from .batch_study import BatchStudy as BatchStudy

# pybamm_data
from .pybamm_data import DataLoader as DataLoader

# dispatch
from .dispatch import parameter_sets as parameter_sets
from .dispatch import Model as Model

# ============================================================================
# SUBMODULE ALIASES
# These are handled by custom __getattr__ in __init__.py, not lazy_loader.
# They are documented here for reference but not included in the stub imports
# because lazy_loader cannot handle aliasing nested submodules to top level.
#
# Available submodule aliases:
#   pybamm.active_material -> pybamm.models.submodels.active_material
#   pybamm.callbacks -> pybamm.callbacks
#   pybamm.constants -> pybamm.parameters.constants
#   pybamm.convection -> pybamm.models.submodels.convection
#   pybamm.current_collector -> pybamm.models.submodels.current_collector
#   pybamm.electrode -> pybamm.models.submodels.electrode
#   pybamm.electrolyte_conductivity -> pybamm.models.submodels.electrolyte_conductivity
#   pybamm.electrolyte_diffusion -> pybamm.models.submodels.electrolyte_diffusion
#   pybamm.equivalent_circuit -> pybamm.models.full_battery_models.equivalent_circuit
#   pybamm.equivalent_circuit_elements -> pybamm.models.submodels.equivalent_circuit_elements
#   pybamm.experiment -> pybamm.experiment
#   pybamm.external_circuit -> pybamm.models.submodels.external_circuit
#   pybamm.interface -> pybamm.models.submodels.interface
#   pybamm.interface_utilisation -> pybamm.models.submodels.interface.interface_utilisation
#   pybamm.kinetics -> pybamm.models.submodels.interface.kinetics
#   pybamm.lead_acid -> pybamm.models.full_battery_models.lead_acid
#   pybamm.lithium_ion -> pybamm.models.full_battery_models.lithium_ion
#   pybamm.lithium_plating -> pybamm.models.submodels.interface.lithium_plating
#   pybamm.open_circuit_potential -> pybamm.models.submodels.interface.open_circuit_potential
#   pybamm.oxygen_diffusion -> pybamm.models.submodels.oxygen_diffusion
#   pybamm.particle -> pybamm.models.submodels.particle
#   pybamm.particle_mechanics -> pybamm.models.submodels.particle_mechanics
#   pybamm.porosity -> pybamm.models.submodels.porosity
#   pybamm.sei -> pybamm.models.submodels.interface.sei
#   pybamm.sodium_ion -> pybamm.models.full_battery_models.sodium_ion
#   pybamm.standard_spatial_vars -> pybamm.geometry.standard_spatial_vars
#   pybamm.step -> pybamm.experiment.step
#   pybamm.telemetry -> pybamm.telemetry
#   pybamm.thermal -> pybamm.models.submodels.thermal
#   pybamm.transport_efficiency -> pybamm.models.submodels.transport_efficiency
# ============================================================================
