"""
Single source of truth for lazy loading configuration.

Used by both __init__.py (runtime) and generate_pyi_stub.py (stub generation).

This module defines:
- EAGER_IMPORTS: Attributes imported at module load time (wildcard imports)
- LAZY_IMPORTS: Attributes loaded on first access via lazy_loader
- SUBMODULE_ALIASES: Nested submodules exposed at top level (e.g., pybamm.lithium_ion)
"""

# Eagerly loaded items (imported at module load time via wildcard imports)
EAGER_IMPORTS: dict[str, list[str]] = {
    # Logger and settings
    ".logger": ["logger", "set_logging_level", "get_new_logger"],
    ".settings": ["settings"],
    ".citations": ["Citations", "citations", "print_citations"],
    # Expression tree modules (wildcard imports in __init__.py)
    ".expression_tree.symbol": [
        "Symbol",
        "domain_size",
        "create_object_of_size",
        "evaluate_for_shape_using_domain",
        "is_constant",
        "is_scalar_zero",
        "is_scalar_one",
        "is_scalar_minus_one",
        "is_matrix_zero",
        "is_matrix_one",
        "is_matrix_minus_one",
        "simplify_if_constant",
        "convert_to_symbol",
    ],
    ".expression_tree.binary_operators": [
        "BinaryOperator",
        "Power",
        "Addition",
        "Subtraction",
        "Multiplication",
        "KroneckerProduct",
        "TensorProduct",
        "MatrixMultiplication",
        "Division",
        "Inner",
        "Equality",
        "EqualHeaviside",
        "NotEqualHeaviside",
        "Modulo",
        "Minimum",
        "Maximum",
        "softplus",
        "softminus",
        "sigmoid",
        "source",
    ],
    ".expression_tree.concatenations": [
        "Concatenation",
        "NumpyConcatenation",
        "DomainConcatenation",
        "SparseStack",
        "ConcatenationVariable",
        "concatenation",
        "numpy_concatenation",
    ],
    ".expression_tree.unary_operators": [
        "UnaryOperator",
        "Negate",
        "AbsoluteValue",
        "Transpose",
        "Sign",
        "Floor",
        "Ceiling",
        "Index",
        "SpatialOperator",
        "Gradient",
        "Divergence",
        "Laplacian",
        "GradientSquared",
        "Mass",
        "BoundaryMass",
        "Integral",
        "BaseIndefiniteIntegral",
        "IndefiniteIntegral",
        "BackwardIndefiniteIntegral",
        "DefiniteIntegralVector",
        "BoundaryIntegral",
        "OneDimensionalIntegral",
        "DeltaFunction",
        "BoundaryOperator",
        "BoundaryValue",
        "BoundaryMeshSize",
        "ExplicitTimeIntegral",
        "BoundaryGradient",
        "EvaluateAt",
        "UpwindDownwind",
        "UpwindDownwind2D",
        "NodeToEdge2D",
        "Magnitude",
        "Upwind",
        "Downwind",
        "NotConstant",
        "grad",
        "div",
        "laplacian",
        "grad_squared",
        "surf",
        "boundary_value",
        "sign",
        "upwind",
        "downwind",
    ],
    ".expression_tree.averages": [
        "_BaseAverage",
        "XAverage",
        "YZAverage",
        "ZAverage",
        "RAverage",
        "SizeAverage",
        "x_average",
        "yz_average",
        "z_average",
        "r_average",
        "size_average",
    ],
    ".expression_tree.broadcasts": [
        "Broadcast",
        "PrimaryBroadcast",
        "PrimaryBroadcastToEdges",
        "SecondaryBroadcast",
        "SecondaryBroadcastToEdges",
        "TertiaryBroadcast",
        "TertiaryBroadcastToEdges",
        "FullBroadcast",
        "FullBroadcastToEdges",
        "ones_like",
        "zeros_like",
    ],
    ".expression_tree.functions": [
        "Function",
        "SpecificFunction",
        "Arcsinh",
        "Arctan",
        "Cos",
        "Cosh",
        "Erf",
        "Exp",
        "Log",
        "Max",
        "Min",
        "Sin",
        "Sinh",
        "Sqrt",
        "Tanh",
        "arcsinh",
        "arctan",
        "cos",
        "cosh",
        "erf",
        "exp",
        "log",
        "log10",
        "max",
        "min",
        "sin",
        "sinh",
        "sqrt",
        "tanh",
    ],
    ".expression_tree.interpolant": ["Interpolant"],
    ".expression_tree.discrete_time_sum": ["DiscreteTimeData", "DiscreteTimeSum"],
    ".expression_tree.variable": ["VariableBase", "Variable", "VariableDot"],
    ".expression_tree.coupled_variable": ["CoupledVariable"],
    ".expression_tree.independent_variable": [
        "IndependentVariable",
        "Time",
        "SpatialVariable",
        "SpatialVariableEdge",
        "t",
        "KNOWN_COORD_SYS",
    ],
    ".expression_tree.exceptions": [
        "DomainError",
        "OptionError",
        "OptionWarning",
        "GeometryError",
        "ModelError",
        "SolverError",
        "SolverWarning",
        "ShapeError",
        "ModelWarning",
        "DiscretisationError",
        "InvalidModelJSONError",
    ],
    ".expression_tree.scalar": ["Scalar", "Constant"],
    ".expression_tree.state_vector": ["StateVectorBase", "StateVector", "StateVectorDot"],
    ".expression_tree.tensor_field": ["TensorField"],
    ".expression_tree.parameter": ["Parameter", "FunctionParameter"],
    ".expression_tree.input_parameter": ["InputParameter"],
    ".expression_tree.array": ["Array", "linspace", "meshgrid"],
    ".expression_tree.vector_field": ["VectorField"],
    ".expression_tree.matrix": ["Matrix"],
    ".expression_tree.vector": ["Vector"],
}

# Lazily loaded attributes (loaded on first access via lazy_loader)
LAZY_IMPORTS: dict[str, list[str]] = {
    ".util": [
        "root_dir",
        "Timer",
        "TimerTime",
        "FuzzyDict",
        "load",
        "is_constant_and_can_evaluate",
        "get_parameters_filepath",
        "has_jax",
        "get_jax",
        "import_optional_dependency",
    ],
    ".expression_tree.operations.evaluate_python": [
        "find_symbols",
        "id_to_python_variable",
        "to_python",
        "EvaluatorPython",
        "EvaluatorJax",
        "JaxCooMatrix",
    ],
    ".expression_tree.operations.jacobian": ["Jacobian"],
    ".expression_tree.operations.convert_to_casadi": ["CasadiConverter"],
    ".expression_tree.operations.unpack_symbols": ["SymbolUnpacker"],
    ".expression_tree.operations.serialise": ["Serialise", "ExpressionFunctionParameter"],
    ".models.base_model": ["BaseModel", "ModelSolutionObservability", "load_model"],
    ".models.symbol_processor": ["SymbolProcessor"],
    ".models.event": ["Event", "EventType"],
    ".models.full_battery_models.base_battery_model": ["BaseBatteryModel", "BatteryModelOptions"],
    ".models.submodels.base_submodel": ["BaseSubModel"],
    ".geometry.geometry": ["Geometry"],
    ".geometry.battery_geometry": ["battery_geometry"],
    ".parameters.parameter_values": ["ParameterValues", "scalarize_dict", "arrayize_dict"],
    ".parameters.geometric_parameters": ["geometric_parameters", "GeometricParameters"],
    ".parameters.electrical_parameters": ["electrical_parameters", "ElectricalParameters"],
    ".parameters.thermal_parameters": ["thermal_parameters", "ThermalParameters"],
    ".parameters.lithium_ion_parameters": ["LithiumIonParameters"],
    ".parameters.lead_acid_parameters": ["LeadAcidParameters"],
    ".parameters.ecm_parameters": ["EcmParameters"],
    ".parameters.size_distribution_parameters": ["get_size_distribution_parameters", "lognormal"],
    ".discretisations.discretisation": ["Discretisation", "has_bc_of_form"],
    ".meshes.meshes": ["Mesh", "SubMesh", "MeshGenerator"],
    ".meshes.zero_dimensional_submesh": ["SubMesh0D"],
    ".meshes.one_dimensional_submeshes": [
        "SubMesh1D",
        "Uniform1DSubMesh",
        "Exponential1DSubMesh",
        "Chebyshev1DSubMesh",
        "UserSupplied1DSubMesh",
        "SpectralVolume1DSubMesh",
        "SymbolicUniform1DSubMesh",
    ],
    ".meshes.two_dimensional_submeshes": ["SubMesh2D", "Uniform2DSubMesh"],
    ".meshes.scikit_fem_submeshes": [
        "ScikitSubMesh2D",
        "ScikitUniform2DSubMesh",
        "ScikitExponential2DSubMesh",
        "ScikitChebyshev2DSubMesh",
        "UserSupplied2DSubMesh",
    ],
    ".meshes.scikit_fem_submeshes_3d": [
        "ScikitFemSubMesh3D",
        "ScikitFemGenerator3D",
        "UserSuppliedSubmesh3D",
    ],
    ".spatial_methods.spatial_method": ["SpatialMethod"],
    ".spatial_methods.zero_dimensional_method": ["ZeroDimensionalSpatialMethod"],
    ".spatial_methods.finite_volume": ["FiniteVolume"],
    ".spatial_methods.finite_volume_2d": ["FiniteVolume2D"],
    ".spatial_methods.spectral_volume": ["SpectralVolume"],
    ".spatial_methods.scikit_finite_element": ["ScikitFiniteElement"],
    ".spatial_methods.scikit_finite_element_3d": ["ScikitFiniteElement3D"],
    ".solvers.solution": ["Solution", "EmptySolution", "make_cycle_solution"],
    ".solvers.processed_variable_time_integral": ["ProcessedVariableTimeIntegral"],
    ".solvers.processed_variable": [
        "ProcessedVariable",
        "ProcessedVariable2DFVM",
        "process_variable",
        "ProcessedVariableUnstructured",
    ],
    ".solvers.processed_variable_computed": ["ProcessedVariableComputed"],
    ".solvers.summary_variable": ["SummaryVariables"],
    ".solvers.base_solver": ["BaseSolver"],
    ".solvers.dummy_solver": ["DummySolver"],
    ".solvers.algebraic_solver": ["AlgebraicSolver"],
    ".solvers.casadi_solver": ["CasadiSolver"],
    ".solvers.casadi_algebraic_solver": ["CasadiAlgebraicSolver"],
    ".solvers.scipy_solver": ["ScipySolver"],
    ".solvers.composite_solver": ["CompositeSolver"],
    ".solvers.jax_solver": ["JaxSolver"],
    ".solvers.jax_bdf_solver": ["jax_bdf_integrate"],
    ".solvers.idaklu_jax": ["IDAKLUJax"],
    ".solvers.idaklu_solver": ["IDAKLUSolver"],
    ".experiment.experiment": ["Experiment"],
    ".plotting.quick_plot": ["QuickPlot", "close_plots", "QuickPlotAxes"],
    ".plotting.plot": ["plot"],
    ".plotting.plot2D": ["plot2D"],
    ".plotting.plot_voltage_components": ["plot_voltage_components"],
    ".plotting.plot_thermal_components": ["plot_thermal_components"],
    ".plotting.plot_summary_variables": ["plot_summary_variables"],
    ".plotting.dynamic_plot": ["dynamic_plot"],
    ".plotting.plot_3d_cross_section": ["plot_3d_cross_section"],
    ".plotting.plot_3d_heatmap": ["plot_3d_heatmap"],
    ".simulation": ["Simulation", "load_sim", "is_notebook"],
    ".batch_study": ["BatchStudy"],
    ".pybamm_data": ["DataLoader"],
    ".dispatch": ["parameter_sets", "models", "Model"],
}

# Submodule aliases - nested submodules exposed at top level
SUBMODULE_ALIASES: dict[str, str] = {
    "lead_acid": ".models.full_battery_models.lead_acid",
    "lithium_ion": ".models.full_battery_models.lithium_ion",
    "equivalent_circuit": ".models.full_battery_models.equivalent_circuit",
    "sodium_ion": ".models.full_battery_models.sodium_ion",
    "active_material": ".models.submodels.active_material",
    "convection": ".models.submodels.convection",
    "current_collector": ".models.submodels.current_collector",
    "electrolyte_conductivity": ".models.submodels.electrolyte_conductivity",
    "electrolyte_diffusion": ".models.submodels.electrolyte_diffusion",
    "electrode": ".models.submodels.electrode",
    "external_circuit": ".models.submodels.external_circuit",
    "interface": ".models.submodels.interface",
    "oxygen_diffusion": ".models.submodels.oxygen_diffusion",
    "particle": ".models.submodels.particle",
    "porosity": ".models.submodels.porosity",
    "thermal": ".models.submodels.thermal",
    "transport_efficiency": ".models.submodels.transport_efficiency",
    "particle_mechanics": ".models.submodels.particle_mechanics",
    "equivalent_circuit_elements": ".models.submodels.equivalent_circuit_elements",
    "kinetics": ".models.submodels.interface.kinetics",
    "sei": ".models.submodels.interface.sei",
    "lithium_plating": ".models.submodels.interface.lithium_plating",
    "interface_utilisation": ".models.submodels.interface.interface_utilisation",
    "open_circuit_potential": ".models.submodels.interface.open_circuit_potential",
    "standard_spatial_vars": ".geometry.standard_spatial_vars",
    "constants": ".parameters.constants",
    "experiment": ".experiment",
    "step": ".experiment.step",
    "callbacks": ".callbacks",
    "telemetry": ".telemetry",
}
