name: Run benchmarks on push
on:
  push:
    branches: [main]


permissions: {}

concurrency:
  # Cancel intermediate builds always
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYBAMM_DISABLE_TELEMETRY: "true"

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python 3.13
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.13


      - name: Install Linux system dependencies
        run: |
          sudo apt-get update
          sudo apt install gfortran gcc libopenblas-dev

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install python dependencies
        run: uv pip install --system asv

      - name: Fetch base branch
        run: |
          # This workflow also runs for merge commits
          # on main. In this case, we don't want to be
          # fetching the main branch.
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          # This workflow should also run on forks; hence,
          # we should fetch the upstream main branch.
          git remote add upstream https://github.com/pybamm-team/PyBaMM/
          if [ $current_branch != "main" ]; then
              git fetch upstream main:main
          fi

      - name: Run benchmarks
        run: |
          asv machine --machine "GitHubRunner"
          # Get IDs of branch and PR commits
          BASE_COMMIT=$(git rev-parse main)
          HEAD_COMMIT=$(git rev-parse HEAD)
          echo $BASE_COMMIT | tee commits_to_compare.txt
          echo $HEAD_COMMIT | tee -a commits_to_compare.txt
          asv run HASHFILE:commits_to_compare.txt --m "GitHubRunner" --show-stderr -v

      - name: Compare commits' benchmark results
        run: |
          BASE_COMMIT=$(head -1 commits_to_compare.txt)
          HEAD_COMMIT=$(tail -1 commits_to_compare.txt)
          echo "SUMMARY OF CHANGES"
          echo "=================="
          asv compare $BASE_COMMIT $HEAD_COMMIT | tee compare_result.txt
          # Make sure grep returns error code 0 even if code 1 is
          # returned because no match is found
          REGRESSIONS=$({ grep "+" compare_result.txt || test $? = 1; })
          if [ ! -z "$REGRESSIONS" ]; \
          then \
          echo "REGRESSIONS FOUND"; \
          echo "================="; \
          echo "$REGRESSIONS"; \
          echo "================="; \
          printf "Found %d regression(s)\n" $(echo "$REGRESSIONS" | wc -l); \
          exit 1; \
          fi
